{main:{
	"Judge Familiar":4, 
	"Dryad Militant":4, 
	"Mana Tithe":4, 
	"Path to Exile":4, 
	"Phyrexian Revoker":4, 
	"Leonin Arbiter":4, 
	"Thalia, Guardian of Thraben":2, 
	"Samurai of the Pale Curtain":2, 
	"Aven Mindcensor":4, 
	"Vryn Wingmare":3, 
	"Thalia, Heretic Cathar":2, 
	"Elspeth, Knight Errant":1, 
	"Ghost Quarter":4, 
	"Tectonic Edge":3, 
	"Plains":15, 
},side:{
	"Aura of Silence":1, 
	"Burrenton Forge-Tender":3, 
	"Disenchant":2, 
	"Mirran Crusader":2, 
	"Rest in Peace":3, 
	"Stony Silence":2, 
	"Wrath of God":2, 
}}
