{main:{
	"Dismember":2, 
	"Funeral Charm":2, 
	"Smallpox":3, 
	"Wrench Mind":4, 
	"Inquisition of Kozilek":4, 
	"Raven's Crime":4, 
	"Thoughtseize":3, 
	"Liliana's Caress":2, 
	"Shrieking Affliction":4, 
	"Liliana of the Veil":3, 
	"Ensnaring Bridge":3, 
	"The Rack":4, 
	"Bojuka Bog":1, 
	"Urborg, Tomb of Yawgmoth":3, 
	"Mutavault":4, 
	"Swamp":14, 
},side:{
	"Ensnaring Bridge ":1, 
	"Grafdigger's Cage ":2, 
	"Pithing Needle ":2, 
	"Fulminator Mage":2, 
	"Damnation ":2, 
	"Relic of Progenitu":2, 
	"Leyline of the Void":3, 
	"Grasp of Darkness":1, 
}}
