{
	main:{
		"Temple Garden":1, 
		"Godless Shrine":1, 
		"Marsh Flats":1, 
		"Razorverge Thicket":1, 
		"Windswept Heath":4, 
		"Verdant Catacombs":3, 
		"Overgrown Tomb":2, 
		"Polluted Delta":1, 
		"Gavony Township":1, 
		"Swamp":2, 
		"Forest":1, 
		"Plains":1, 
		"Ghost Quarter":1, 
		"Hissing Quagmire":1, 
		"Shambling Vent":1, 
		"Concealed Courtyard":2, 
		"Kalitas, Traitor of Ghet":2, 
		"Scavenging Ooze":3, 
		"Inquisition of Kozilek":4, 
		"Lingering Souls":4, 
		"Path to Exile":4, 
		"Abrupt Decay":3, 
		"Tarmogoyf":4, 
		"Liliana of the Veil":3, 
		"Thoughtseize":2, 
		"Siege Rhino":3, 
		"Gideon, Ally of Zendikar":1, 
		"Maelstrom Pulse":2, 
		"Murderous Cut":1, 
	},
	side:{
		"Duress":2, 
		"Pithing Needle":2, 
		"Feed the Clan":2, 
		"Relic of Progenitus":2, 
		"Thrun, the Last Troll":1, 
		"Wrath of God":2, 
		"Beast Within":2, 
		"Anguished Unmaking":2, 
	}
}
