{
	main:{
		'Temple Garden':1,
		'Godless Shrine':1,
		'Marsh Flats':1,
		'Razorverge Thicket':1,
		'Windswept Heath':4,
		'Verdant Catacombs':3,
		'Overgrown Tomb':1,
		'Polluted Delta':1,
		'Gavony Township':2,
		'Swamp':2,
		'Forest':2,
		'Plains':1,
		'Ghost Quarter':2,
		'Noble Hierarch':3,
		'Inquisition of Kozilek':2,
		'Birds of Paradise':2,
		'Lingering Souls':2,
		'Path to Exile':4,
		'Abrupt Decay':3,
		'Voice of Resurgence':4,
		'Loxodon Smiter':4,
		'Kitchen Finks':2,
		'Siege Rhino':4,
		'Wilt-Leaf Liege':3,
		'Anafenza, the Foremost':3,

	},
	side:{
		'Duress':2,
		'Zealous Persecution ':2,
		'Kor Firewalker':2,
		'Choke':2,
		'Kalitas, Traitor of Ghet':1,
		'Kataki, War\'s Wage':2,
		'Murderous Cut':2,
		'Relic of Progenitus':2,
	}
}
