{main:{
		"Darkslick Shores":4, 
		"Gemstone Mine":4, 
		"Island":1, 
		"Plains":1, 
		"Seachrome Coast":4, 
		"Temple of Deceit":4, 
		"Temple of Enlightenment":2, 
		"Ad Nauseam":4, 
		"Angel's Grace":4, 
		"Lightning Storm":1, 
		"Lotus Bloom":4, 
		"Pact of Negation":3, 
		"Pentad Prism":4, 
		"Phyrexian Unlife":4, 
		"Serum Visions":4, 
		"Sleight of Hand":4, 
		"Spoils of the Vault":3, 
		"Laboratory Maniac":1, 
		"Simian Spirit Guide":4, 
	},
	side:{
		"Ethereal Haze":3, 
		"Hurkyl's Recall":2, 
		"Leyline of Sanctity":4, 
		"Pact of Negation":1, 
		"Silence":1, 
		"Slaughter Pact":1, 
		"Thoughtseize":3, 
	}
}
