{
	main:{
		'Simian Spirit Guide':4,
		'Laboratory Maniac':1,
		'Pentad Prism':4,
		'Lotus Bloom':4,
		'Phyrexian Unlife':3,
		'Sleight of Hand':4,
		'Serum Visions':4,
		'Ad Nauseam':4,
		"Angel's Grace":4,
		"Pact of Negation":3,
		"Slaughter Pact":1,
		"Spoils of the Vault":3,
		"Lightning Storm":1,
		"Plains":1,
		"Swamp":1,
		"Island":1,
		"Polluted Delta":2,
		"Gemstone Mine":3,
		"Hallowed Fountain":1,
		"Temple of Enlightment":2,
		"Flood Strand":1,
		"Tolaria West":1,
		"Watery Grave":1,
		"Seachrome Coast":1,
		"Boseiju, Who Shelters All":1,
		"Temple of Deceit":1,
		"Urborg, Yawgmoth's Tomb":1,
		"Dreadship Reef":1,
	},
	side:{
		'Echoing Truth':1,
		'Duress':1,
		"Silence":1,
		"Thoughtseize":1,
		"Patrician's Scorn":1,
		"Leyline of Sanctity":4,
		"Hurky'ls Recall":1,
		"Nihil Spellbomb":1,
		"Slaughter Pact":1,
		"Phyrexian Unlife":1,
		"Ethereal Haze":1,
	}
}
