{
	main:{
		"Arid Mesa":1, 
		"Blood Crypt":1, 
		"Bloodghast":4, 
		"Bloodstained Mire":1, 
		"Collective Brutality":1, 
		"Conflagrate":3, 
		"Copperline Gorge":3, 
		"Dakmor Salvage":2, 
		"Faithless Looting":4, 
		"Golgari Grave-Troll":4, 
		"Haunted Dead":1, 
		"Insolent Neonate":4, 
		"Life from the Loam":3, 
		"Mountain":3, 
		"Narcomoeba":4, 
		"Prized Amalgam":4, 
		"Scalding Tarn":2, 
		"Steam Vents":1, 
		"Stinkweed Imp":4, 
		"Stomping Ground":2, 
		"Tormenting Voice":4, 
		"Wooded Foothills":4, 
	},
	side:{
		"Ancient Grudge":2, 
		"Collective Brutality":2, 
		"Darkblast":1, 
		"Engineered Explosives":3, 
		"Gnaw to the Bone":2, 
		"Lightning Axe":1, 
		"Nature's Claim":1, 
		"Thoughtseize":2, 
		"Vengeful Pharaoh":1, 
	}
}
