{main:{
	"Vault Skirge":4, 
	"Master of Etherium":2, 
	"Etched Champion":2, 
	"Ornithopter":4, 
	"Steel Overseer":4, 
	"Memnite":2, 
	"Spellskite":2, 
	"Arcbound Ravager":4, 
	"Signal Pest":4, 
	"Galvanic Blast":4, 
	"Cranial Plating":4, 
	"Mox Opal":4, 
	"Springleaf Drum":4, 
	"Glimmervoid":3, 
	"Mountain":1, 
	"Inkmoth Nexus":4, 
	"Darksteel Citadel":4, 
	"Blinkmoth Nexus":4, 
},side:{
	"Wear // Tear":2, 
	"Ghirapur Aether Grid":1, 
	"Relic of Progenitus":2, 
	"Blood Moon":2, 
	"Grafdigger's Cage":1, 
	"Thoughtseize":2, 
	"Whipflare":2, 
	"Torpor Orb":1, 
	"Spell Pierce":2, 
}}
