{
	main:{
		"Wall of Omens":4, 
		"Blade Splicer":3, 
		"Restoration Angel":4, 
		"Kiki-Jiki, Mirror Breaker":1, 
		"Emrakul, the Aeons Torn":1, 
		"Condemn":1, 
		"Lightning Bolt":4, 
		"Path to Exile":4, 
		"Magma Jet":2, 
		"Lightning Helix":3, 
		"Anger of the Gods":1, 
		"Blood Moon":3, 
		"Nahiri, the Harbinger":4, 
		"Ghost Quarter":1, 
		"Mountain":1, 
		"Tectonic Edge":1, 
		"Clifftop Retreat":2, 
		"Needle Spires":2, 
		"Sacred Foundry":2, 
		"Temple of Triumph":3, 
		"Arid Mesa":4, 
		"Flooded Strand":4, 
		"Plains":5, 
	},
	side:{
		"Engineered Explosives":1, 
		"Wear // Tear":2, 
		"Celestial Purge":1, 
		"Lightning Helix":1, 
		"Rest in Peace":2, 
		"Stony Silence":2, 
		"Anger of the Gods":1, 
		"Eidolon of Rhetoric":1, 
		"Ajani Vengeant":1, 
		"Crumble to Dust":1, 
		"Wrath of God":1, 
		"Batterskull":1, 
	}
}
