{
	main:{
		"Funeral Charm":2, 
		"Thoughtseize":3, 
		"Inquisition of Kozilek":4, 
		"Raven's Crime":4, 
		"Shrieking Affliction":4, 
		"The Rack":4, 
		"Victim of Night":3, 
		"Smallpox":4, 
		"Wrench Mind":4, 
		"Liliana of the Veil":4, 
		"Dakmor Salvage":1, 
		"Mutavault":4, 
		"Urborg, Tomb of Yawgmoth":4, 
		"Swamp":15, 
	},
	side:{
		"Darkblast":1, 
		"Extirpate":1, 
		"Grafdigger's Cage":1, 
		"Nihil Spellbomb":1, 
		"Pithing Needle":1, 
		"Bile Blight":1, 
		"Ratchet Bomb":1, 
		"Victim of Night":1, 
		"Flaying Tendrils":1, 
		"Syphon Life":1, 
		"Vampire Nighthawk":1, 
		"Nyxathid":2, 
		"Mutilate":1, 
		"Night of Souls' Betrayal":1, 
	}
}
