{main:{
	"Emrakul, the Aeons Torn":1, 
	"Deceiver Exarch":1, 
	"Glen Elendra Archmage":1, 
	"Kiki-Jiki, Mirror Breaker":1, 
	"Noble Hierarch":1, 
	"Pia and Kiran Nalaar":1, 
	"Qasali Pridemage":1, 
	"Scavenging Ooze":1, 
	"Spellskite":1, 
	"Eternal Witness":2, 
	"Restoration Angel":2, 
	"Wall of Omens":2, 
	"Wall of Roots":3, 
	"Voice of Resurgence":4, 
	"Birds of Paradise":4, 
	"Path to Exile":4, 
	"Chord of Calling":4, 
	"Nahiri, the Harbinger":4, 
	"Breeding Pool":1, 
	"Fire-Lit Thicket":1, 
	"Hallowed Fountain":1, 
	"Horizon Canopy":1, 
	"Mountain":1, 
	"Plains":1, 
	"Sacred Foundry":1, 
	"Temple Garden":1, 
	"Razorverge Thicket":1, 
	"Sunpetal Grove":1, 
	"Raging Ravine":1, 
	"Forest":2, 
	"Stomping Ground":2, 
	"Windswept Heath":4, 
	"Wooded Foothills":4, 
},side:{
	"Engineered Explosives":3,
	"Lightning Helix":3, 
	"Fulminator Mage":2, 
	"Scavenging Ooze":1, 
	"Eidolon of Rhetoric":1, 
	"Reclamation Sage":1, 
	"Kitchen Finks":1, 
	"Izzet Staticaster":1, 
	"Kataki, War's Wage":1, 
	"Kor Firewalker":1, 
}}
