{
	main:{
		"Pyromancer Ascension":2, 
		"Jeskai Ascendancy":4, 
		"Fatestitcher":4, 
		"Serum Visions":4, 
		"Thought Scour":4, 
		"Gitaxian Probe":4, 
		"Lightning Bolt":4, 
		"Visions of Beyond":3, 
		"Flooded Strand":4, 
		"Scalding Tarn":2, 
		"Hallowed Fountain":1, 
		"Steam Vents":2, 
		"Island":2, 
		"Sleight of Hand":4, 
		"Path to Exile":4, 
		"Mountain":1, 
		"Arid Mesa":1, 
		"Seachrome Coast":1, 
		"Faerie Conclave":1, 
		"Remand":4, 
		"Plains":1, 
		"Glacial Fortress":1, 
		"Spirebluff Canal":1, 
		"Izzet Charm":1, 
	},
	side:{
		"Timely Reinforcements":2, 
		"Wear // Tear":2, 
		"Monastery Mentor":2, 
		"Dispel":2, 
		"Young Pyromancer":3, 
		"Lightning Helix":1, 
		"Anger of the Gods":2, 
		"Stony Silence":1, 
	}
}
