{
	main:{
		'Flooded Strand':4,
		'Scalding Tarn':3,
		'Plains':1,
		'Mountain':1,
		'Island':2,
		'Faerie Conclave':1,
		'Sulfur Falls':1,
		'Hallowed Fountain':1,
		'Steam Vents':2,
		'Glacial Fortress':2,
		'Fatestitcher':4,
		'Lightning Bolt':4,
		'Thought Scour':4,
		'Sleight of Hand':4,
		'Path to Exile':4,
		'Visions of Beyond':3,
		'Gitaxian Probe':4,
		'Serum Visions':4,
		'Remand':4,
		'Jeskai Ascendancy':4,
		'Pyromancer Ascension':3,
	},
	side:{
		'Monastery Mentor':2,
		'Young Pyromancer':3,
		'Negate':1,
		'Dispel':2,
		'Hurkyl\'s Recall':1,
		'Wear // Tear':2,
		'Timely Reinforcements':3,
		'Spell Pierce':1,
	}
}
