
{
	main:{
		"Birds Of Paradise":4 ,
		"Noble Hierarch":3 ,
		"Wall of Roots":2 ,
		"Viscera Seer":3 ,
		"Anafenza, Kin-tree spirit":2 ,
		"Melira, Sylvok Outcast":2 ,
		"Scavenging Ooze":1 ,
		"Kitchen Finks":4 ,
		"Eternal Witness":3 ,
		"Murderous Redcap":1 ,
		"Restoration Angel":1 ,
		"Sin Collector":1 ,
		"Spellskite":1 ,
		"Fiend Hunter":1 ,
		"Qasali Pridemage":1 ,
		"Chord of Calling":4 ,
		"Collected Company":4 ,
		"Windswept Heath":4 ,
		"Verdant Catacombs":4 ,
		"Temple Garden":2 ,
		"Overgrown Tomb":2 ,
		"Godless Shrine":1 ,
		"Forest":2 ,
		"Plains":1 ,
		"Swamp":1 ,
		"Horizon Canopy":2 ,
		"Gavony Township":3 ,

	},
	side:{
		"Fulminator Mage":3 ,
		"Path to Exile":2 ,
		"Thrun, The Last Troll":2 ,
		"Reclamation Sage":1 ,
		"Eidolon of Rhetoric":1 ,
		"Sin Collector":1 ,
		"Tidehollow Sculler":2 ,
		"Abrupt Decay":2 ,
		"Orzhov Pontiff":1 ,
	}
}
