{main:{"Spell Queller":4, 
	"Rattlechains":4, 
	"Geist of Saint Traft":2, 
	"Noble Hierarch":4, 
	"Drogskol Captain":4, 
	"Mausoleum Wanderer":4, 
	"Selfless Spirit":4, 
	"Kira, Great Glass-Spinner":4, 
	"Blessed Alliance":1, 
	"Path to Exile":4, 
	"Collected Company":4, 
	"Tamiyo, Field Researcher":1, 
	"Flooded Strand":4, 
	"Windswept Heath":4, 
	"Botanical Sanctum":1, 
	"Island":2, 
	"Forest":1, 
	"Plains":1, 
	"Temple Garden":1, 
	"Cavern of Souls":1, 
	"Ghost Quarter":1, 
	"Eiganjo Castle":1, 
	"Breeding Pool":1, 
	"Moorland Haunt":1, 
	"Gavony Township":1, 
	"Hallowed Fountain":2, 
	"Horizon Canopy":1, 
},side:{
	"Steel of the Godhead":1, 
	"Detention Sphere":2, 
	"Eidolon of Rhetoric":2, 
	"Engineered Explosives":1, 
	"Chalice of the Void":1, 
	"Spellskite":1, 
	"Supreme Verdict":1, 
	"Kataki, War's Wage":2, 
	"Nature's Claim":1, 
	"Dispel":1, 
	"Rest in Peace":2, 
}}
