{
	main:{
		'Windswept Heath':4,
		'Flooded Strand':4,
		'Temple Garden':3,
		'Gavony Township':3,
		'Breeding Pool':2,
		'Horizon Canopy':2,
		'Hallowed Fountain':1,
		'Wooded Foothills':1,
		'Plains':1,
		'Forest':1,
		'Island':2,
		'Voice of Resurgence':4,
		'Noble Hierarch':4,
		'Flickerwisp':4,
		'Reflector Mage':4,
		'Scavenging Ooze':3,
		'Qasali Pridemage':3,
		'Geist of Saint Traft':3,
		'Birds of Paradise':2,
		'Eternal Witness':2,
		'Phantasmal Image':2,
		'Collected Company':4,
		'Path to Exile':4,
	},
	side:{
		'Burrenton Forge-Tender':3,
		'Kataki, War\'s Wage':3,
		'Kitchen Finks':3,
		'Wrath of God':2,
		'Spellskite':2,
		'Scavenging Ooze':2,
		'Engineered Explosives':2,
	}
}
