{
	main:{
		"Sakura-Tribe Elder":4, 
		"Primeval Titan":4, 
		"Summoner's Pact":3, 
		"Through the Breach":4, 
		"Courser of Kruphix":2, 
		"Oath of Nissa":2, 
		"Emrakul, the Aeons Torn":1, 
		"Scapeshift":2, 
		"Anger of the Gods":2, 
		"Farseek":4, 
		"Search for Tomorrow":4, 
		"Nahiri, the Harbinger":3, 
		"Cinder Glade":3, 
		"Forest":2, 
		"Valakut, the Molten Pinnacle":4, 
		"Plains":1, 
		"Stomping Ground":4, 
		"Wooded Foothills":4, 
		"Mountain":5, 
		"Windswept Heath":1, 
		"Sacred Foundry":1, 
	},
	side:{
		"Anger of the Gods":1, 
		"Crumble to Dust":2, 
		"Obstinate Baloth":3, 
		"Ancient Grudge":1, 
		"Krosan Grip":2, 
		"Relic of Progenitus":2, 
		"Boil":1, 
		"Sudden Shock":3, 
	}
}
