{
main:{
	"Battlefield Forge":4, 
	"Ghost Quarter":4, 
	"Inspiring Vantage":4, 
	"Mountain":1, 
	"Needle Spires":2, 
	"Plains":1, 
	"Rugged Prairie":1, 
	"Sacred Foundry":3, 
	"Tectonic Edge":2, 
	"Alesha, Who Smiles at Death":2, 
	"Eldrazi Displacer":3, 
	"Flickerwisp":3, 
	"Fulminator Mage":2, 
	"Leonin Arbiter":4, 
	"Pia and Kiran Nalaar":3, 
	"Restoration Angel":3, 
	"Selfless Spirit":2, 
	"Thalia, Guardian of Thraben":4, 
	"Thalia, Heretic Cathar":2, 
	"Lightning Bolt":3, 
	"Path to Exile":3, 
	"Æther Vial":4, 
},
side:{
"Burrenton Forge-Tender":3, 
"Eidolon of Rhetoric":3, 
"Forked Bolt":1, 
"Fragmentize":1, 
"Lightning Bolt":1, 
"Path to Exile":1, 
"Rest in Peace":3, 
"Wear // Tear":2, 
},
}
