{
	main:{
		"Anger of the Gods":2 ,
		"Arid Mesa":4 ,
		"Batterskull":1 ,
		"Battlefield Forge":2 ,
		"Blade Splicer":2 ,
		"Blood Moon":3 ,
		"Clifftop Retreat":2 ,
		"Emrakul, the Aeons Torn":1 ,
		"Flooded Strand":4 ,
		"Ghost Quarter":1 ,
		"Kiki-Jiki, Mirror Breaker":1 ,
		"Lightning Bolt":4 ,
		"Lightning Helix":3 ,
		"Magma Jet":2 ,
		"Mountain":1 ,
		"Nahiri, the Harbinger":4 ,
		"Needle Spires":1 ,
		"Path to Exile":4 ,
		"Plains":4 ,
		"Restoration Angel":4 ,
		"Sacred Foundry":2 ,
		"Tectonic Edge":1 ,
		"Temple of Triumph":3 ,
		"Wall of Omens":4 ,
	},
	side:{
		"Ajani Vengeant":1 ,
		"Celestial Purge":1 ,
		"Eidolon of Rhetoric":1 ,
		"Kor Firewalker":3 ,
		"Pithing Needle":1 ,
		"Relic of Progenitus":2 ,
		"Stony Silence":2 ,
		"Timely Reinforcements":1 ,
		"Wear // Tear":2 ,
		"Wrath of God":1 ,
	}
}
