{
	main:{
		'Forest':2,
		'Swamp':1,
		'Plains':1,
		'Gavony Township':2,
		'Verdant Catacombs':4,
		'Windswept Heath':4,
		'Temple Garden':3,
		'Godless Shrine':2,
		'Overgrown Tomb':2,

		'Birds of Paradise':4,
		'Noble Hierarch':4,
		'Wall of Roots':2,
		'Kitchen Finks':4,
		'Melira, Sylvok Outcast':2,
		'Anafenza, Kin-Tree Spirit':2,
		'Qasali Pridemage':1,
		'Eternal Witness':3,
		'Viscera Seer':3,
		'Spellskite':1,
		'Fiend Hunter':1,
		'Orzhov Pontiff':1,
		'Scavenging Ooze':1,
		'Murderous Redcap':1,
		'Blood Artist':1,
		'Collected Company':4,
		'Chord of Calling':3,
		'Abrupt Decay':1,
		'Voice of Resurgence':2,
		'Archangel of Thune':1,
	},
	side:{
		'Tidehollow Sculler':2,
		'Scavenging Ooze':1,
		'Sin Collector':1,
		'Kataki, War\'s Wage':1,
		'Spellskite':1,
		'Fiend Hunter':1,
		'Pithing Needle':2,
		'Path to Exile':2,
		'Abrupt Decay':2,
		'Choke':2,
	}
}
