{
	main:{
		"Grim Lavamancer":2,
		"Wild Nacatl":4,
		"Eidolon of the Great Revel":4, 
		"Goblin Guide":4,
		"Monastery Swiftspear":4,
		"Lava Spike":4,
		"Lightning Bolt":4,
		"Atarka's Command":4,
		"Boros Charm":4,
		"Searing Blaze":4,
		"Rift Bolt":3,
		"Become Immense":1, 
		"Bloodstained Mire":4,
		"Wooded Foothills":4,
		"Arid Mesa":4,
		"Sacred Foundry":3,
		"Stomping Ground":2,
		"Mountain":2,
	},
	side:{
		"Path to Exile":3,
		"Destructive Revelry":3,
		"Deflecting Palm":2,
		"Skullcrack":2,
		"Stony Silence":2,
		"Kor Firewalker":2,
		"Grafdigger's Cage":1, 
	}
}
