{
	main:{
		"Fiend Hunter":1 ,
		"Murderous Redcap":1 ,
		"Orzhov Pontiff":1 ,
		"Anafenza, Kin-Tree Spirit":2 ,
		"Melira, Sylvok Outcast":2 ,
		"Spellskite":2 ,
		"Viscera Seer":2 ,
		"Voice of Resurgence":2 ,
		"Wall of Roots":2 ,
		"Eternal Witness":3 ,
		"Noble Hierarch":3 ,
		"Birds of Paradise":4 ,
		"Kitchen Finks":4 ,
		"Chord of Calling":4 ,
		"Collected Company":4 ,
		"Godless Shrine":1 ,
		"Plains":1 ,
		"Swamp":1 ,
		"Forest":2 ,
		"Gavony Township":2 ,
		"Horizon Canopy":2 ,
		"Overgrown Tomb":2 ,
		"Razorverge Thicket":2 ,
		"Temple Garden":2 ,
		"Verdant Catacombs":4 ,
		"Windswept Heath":4 ,
	},
	side:{
		"Path to Exile":3,
		"Abrupt Decay":2,
		"Thoughtseize":2,
		"Sin Collector":1,
		"Phyrexian Revoker":1,
		"Qasali Pridemage":1,
		"Scavenging Ooze":1,
		"Reveillark":1,
		"Linvala, Keeper of Silence":1,
		"Intrepid Hero":1,
		"Kataki, War's Wage":1,
	}
}
