{
	main:{
		"Jeskai Ascendancy":4, 
		"Fatestitcher":4, 
		"Path to Exile":4, 
		"Lightning Bolt":4, 
		"Remand":4, 
		"Thought Scour":4, 
		"Serum Visions":4, 
		"Sleight of Hand":4, 
		"Gitaxian Probe":4, 
		"Visions of Beyond":3, 
		"Pyromancer Ascension":2, 
		"Bedlam Reveler":1, 
		"Flooded Strand":4, 
		"Scalding Tarn":1, 
		"Arid Mesa":2, 
		"Steam Vents":2, 
		"Hallowed Fountain":1, 
		"Faerie Conclave":1, 
		"Glacial Fortress":2, 
		"Sulfur Falls":1, 
		"Island":2, 
		"Plains":1, 
		"Mountain":1, 
	},
	side:{
		"Monastery Mentor":2, 
		"Young Pyromancer":3, 
		"Enginedeed Explosves":2, 
		"Lightning Helix":1, 
		"Timely Reinforcements":2, 
		"Rest for the Weary":1, 
		"Dispel":2, 
		"Wear // Tear":2, 
	}
}
