{main:{
		"Goblin Guide":4, 
		"Wild Nacatl":4, 
		"Reckless Bushwhacker":4, 
		"Burning-Tree Emissary":4, 
		"Experiment One":4, 
		"Vexing Devil":2, 
		"Ghor-Clan Rampager":2, 
		"Kird Ape":4, 
		"Lightning bolt":4, 
		"Mutagenic Growth":2, 
		"Atarka's command":4, 
		"Path to exile":3, 
		"Sacred foundry":2, 
		"Temple garden ":1, 
		"Stomping ground":3, 
		"Arid Mesa":2, 
		"Wooded foothills":4, 
		"Windswept heath":4, 
		"Mountains":1, 
		"Forest":2, 
},side:{
		"Grim Lavamancer":1, 
		"Lightning Helix":2, 
		"Destructive Revelry":2, 
		"Scavenging Ooze":2, 
		"Molten Rain":2, 
		"Ancient Grudge":1, 
		"Path to exile":1, 
		"Spellskite":1, 
		"Phyrexian Unlife":1, 
		"Grafdigger's Cage":2, 
}}
