{
	main:{
		'Misty Rainforest':4,
		'Scalding Tarn':4,
		'Steam Vents':3,
		'Island':4,
		'Mountain':1,
		'Sulfur Falls':2,
		'Mutavault':1,
		'Wandering Fumarole':1,
		'Faerie Conclave':2,
		'Delver of Secrets':4,
		'Snapcaster Mage':4,
		'Grim Lavamancer':1,
		'Jace, Vryn\'s Prodigy':1,
		'Vendilion Clique':1,
		'Lightning Bolt':4,
		'Anger of the Gods':1,
		'Burst Lightning':1,
		'Flame Slash':1,
		'Cryptic Command':3,
		'Dispel':1,
		'Electrolyze':3,
		'Mana Leak':2,
		'Remand':4,
		'Serum Visions':4,
		'Spell Snare':2,
		'Vapor Snag':1,
	},
	side:{
		'Anger of the Gods':1,
		'Blood Moon':2,
		'Dispel':1,
		'Engineered Explosives':1,
		'Magma Spray':1,
		'Molten Rain':2,
		'Negate':1,
		'Relic of Progenitus':1,
		'Rending Volley':1,
		'Roast':1,
		'Spell Pierce':1,
		'Spellskite':1,
	}
}
