{
	main:{
		"Forest":2,
		"Ghost Quarter":1,
		"Godless Shrine":1,
		"Marsh Flats":2,
		"Overgrown Tomb":2,
		"Plains":1,
		"Polluted Delta":1,
		"Shambling Vent":1,
		"Stirring Wildwood":1,
		"Swamp":1,
		"Temple Garden":1,
		"Treetop Village":2,
		"Urborg, Tomb of Yawgmoth":1,
		"Vault of the Archangel":1,
		"Windswept Heath":3,
		"Abrupt Decay":3,
		"Garruk Wildspeaker":2,
		"Lingering Souls":4,
		"Path to Exile":4,
		"Sword of Fire and Ice":1,
		"Sword of War and Peace":1,
		"Vraska the Unseen":1,
		"Birds of Paradise":4,
		"Brimaz, King of Oreskos":1,
		"Doran, the Siege Tower":4,
		"Knight of the Reliquary":2,
		"Restoration Angel":2,
		"Scavenging Ooze":3,
		"Siege Rhino":4,
		"Spellskite":3,
		"Thrun, the Last Troll":1,
	},
	side:{
		"Choke":2,
		"Languish":2,
		"Fulminator Mage":2,
		"Fracturing Gust":2,
		"Engineered Explosives":1,
		"Sorin, Solemn Visitor":1,
		"Obzedat, Ghost Council":1,
		"Ajani, Mentor of Heroes":1,
		"Batterskull":1,
		"Sigarda, Host of Herons":1,
		"Nissa, Worldwaker":1,
	}
}
