{
	main:{
		"Forest":2, 
		"Gavony Township":1, 
		"Godless Shrine":1, 
		"Marsh Flats":2, 
		"Overgrown Tomb":2, 
		"Plains":1, 
		"Polluted Delta":1, 
		"Shambling Vent":1, 
		"Shizo, Death's Storehouse":1, 
		"Stirring Wildwood":1, 
		"Swamp":1, 
		"Temple Garden":1, 
		"Treetop Village":1, 
		"Urborg, Tomb of Yawgmoth":1, 
		"Vault of the Archangel":1, 
		"Verdant Catacombs":1, 
		"Windswept Heath":3, 
		"Abrupt Decay":3, 
		"Garruk Wildspeaker":2, 
		"Lingering Souls":3, 
		"Path to Exile":4, 
		"Sword of Fire and Ice":1, 
		"Sword of Light and Shadow":1, 
		"Birds of Paradise":4, 
		"Brimaz, King of Oreskos":1, 
		"Courser of Kruphix":2, 
		"Doran, the Siege Tower":4, 
		"Qasali Pridemage":1, 
		"Restoration Angel":2, 
		"Scavenging Ooze":3, 
		"Siege Rhino":4, 
		"Spellskite":3, 
		"Thrun, the Last Troll":1, 
	},
	side:{
		"Choke":2, 
		"Languish":2, 
		"Fulminator Mage":2, 
		"Ghostly Prison":2, 
		"Engineered Explosives":1, 
		"Sorin, Solemn Visitor":1, 
		"Qasali Pridemage":1, 
		"Thragtusk":1, 
		"Batterskull":1, 
		"Sigarda, Host of Herons":1, 
		"Eidolon of rhetoric":1, 
	}
}
