{main:{
	"Blood Crypt":2, 
	"Bloodghast":4, 
	"Bloodstained Mire":4, 
	"Cathartic Reunion":4, 
	"Conflagrate":3, 
	"Copperline Gorge":4, 
	"Dakmor Salvage":2, 
	"Faithless Looting":4, 
	"Golgari Grave-Troll":4, 
	"Insolent Neonate":4, 
	"Life from the Loam":3, 
	"Mountain":2, 
	"Narcomoeba":4, 
	"Prized Amalgam":4, 
	"Rally the Peasants":1, 
	"Shriekhorn":1, 
	"Stinkweed Imp":4, 
	"Stomping Ground":2, 
	"Wooded Foothills":4, 
},side:{
	"Abrupt Decay":1, 
	"Ancient Grudge":2, 
	"Bojuka Bog":1, 
	"Collective Brutality":2, 
	"Darkblast":2, 
	"Gnaw to the Bone":1, 
	"Golgari Charm":1, 
	"Lightning Axe":2, 
	"Nature's Claim":3, 
}}
