
	main:{
		"Goblin Guide":4, 
		"Kird Ape":4, 
		"Wild Nacatl":4, 
		"Burning-Tree Emissary":4, 
		"Reckless Bushwacker":4, 
		"Experiment One":3, 
		"Vexing Devil":2, 
		"Flinthoof Boar":1, 
		"Grim Lavamancer":1, 
		"Ghor-Clan Rampager":3, 
		"Atarka's Command":3, 
		"Lighting Bolt":4, 
		"Path to Exile":3, 
		"Mutagenic Growth":2, 
		"Forest":3, 
		"Mountain":4, 
		"Plains":1, 
		"Stomping Ground":1, 
		"Sacred Foundry":1, 
		"Windswept Heath":4, 
		"Wooded Foothills":4, 
	},
	side:{
		"Boros Charm":2, 
		"Lightning Helix":2, 
		"Destructive Revelry":3, 
		"Experiment One":1, 
		"Become Immense":1, 
		"Flinthhoof Boar":2, 
		"Rancor":2, 
		"Mutagenic growth":1, 
		"Chandra, Torch of Defiance":1, 
	},
}
