{
	main:{
		'Matter Reshaper':3,
		'Endless One':2,
		'Drowner of Hope':3,
		'Eldrazi Displacer':4,
		'Eldrazi Mimic':4,
		'Eldrazi Skyspawner':4,
		'Reality Smasher':4,
		'Thought-Knot Seer':4,
		'Dismember':3,
		'Path to Exile':4,
		'Caves of Koilos':1,
		'Urborg, Tomb of Yawhmoth':1,
		'Island':1,
		'Plains':1,
		'Vesuva':1,
		'Wastes':1,
		'Cavern of Souls':2,
		'Hallowed Fountain':2,
		'Flooded Strand':3,
		'Adarkar Wastes':3,
		'Eldrazi Temple':4,
		'Mana Confluence':1,
		'Eye of Ugin':4,
	},
	side:{
		'Rest in Peace':2,
		'Graffdigger\'s Cage':1,
		'Stony Silence':2,
		'Hurkyl\'s Recall':2,
		'Pithing Needle':1,
		'All is Dust':1,
		'Gut Shot':1,
		'Stubborn Denial':2,
		'Cyclonic Rift':1,
		'Spellskite':2,
	}
}
