{
	main:{
		'Matter Reshaper':2,
		'Kozilek, Butcher of Truth':1,
		'Ulamog, the Ceaseless Hunger':2,
		'Conduit of Ruin':3,
		'Eldrazi Displacer':4,
		'Reality Smasher':4,
		'Thought-Knot Seer':4,
		'Dismember':3,
		'Path to Exile':4,
		'Expedition Map':4,
		'Ancient Stirrings':4,
		'Sylvan Scrying':2,
		'Ugin, the Spirit Dragon':2,

		'Forest':1,
		'Plains':1,
		'Cavern of Souls':2,
		'Temple Garden':2,
		'Windswept Heath':4,
		'Eldrazi Temple':4,
		'Urza\'s Mine':4,
		'Urza\'s Tower':4,
		'Urza\'s Power Plant':4,
	},
	side:{
		'Rest in Peace':2,
		'Graffdigger\'s Cage':1,
		'Kataki, War\'s Wage':2,
		'Chalice of the Void':2,
		'All is Dust':1,
		'Leyline of Sanctity':2,
		'Feed the Clan':2,
		'Nature\'s Claim':2,
	}
}
