{
	main:{
		"Dwynen's Elite":4 ,
		"Elvish Archdruid":4 ,
		"Elvish Mystic":4 ,
		"Elvish Visionary":4 ,
		"Heritage Druid":4 ,
		"Llanowar Elves":4 ,
		"Nettle Sentinel":4 ,
		"Reclamation Sage":1 ,
		"Shaman of the Pack":4 ,
		"Ezuri, Renegade Leader":2 ,
		"Chord of Calling":4 ,
		"Collected Company":4 ,
		"Forest":4 ,
		"Cavern of Souls":4 ,
		"Gilt-Leaf Palace":2 ,
		"Razorverge Thicket":4 ,
		"Nykthos, Shrine to Nyx":1 ,
		"Pendelhaven":1 ,
		"Woodland Cemetery":1 ,
		"Overgrown Tomb":1 ,
	},
	side:{
		"Spellskite":2 ,
		"Burrenton Forge-Tender":1 ,
		"Chameleon Colossus":1 ,
		"Phyrexian Revoker":1 ,
		"Essence Warden":2 ,
		"Choke":2 ,
		"Fracturing Gust":1 ,
		"Relic of Progenitus":2 ,
		"Kataki, War's Wage":1 ,
		"Pithing Needle":1 ,
		"Summoning Trap":2 ,
	}
}
