{
main:{
	"Flooded Strand":4 ,
	"Polluted Delta":1 ,
	"Island":2 ,
	"Snow-covered Island":1 ,
	"Plains":1 ,
	"Snow-covered Plains":1 ,
	"Tolaria West":1 ,
	"Hallowed Fountain":2 ,
	"Watery Grave":1 ,
	"Celestial Colonnade":2 ,
	"Glacial Fortress":2 ,
	"Mystic Gate":1 ,
	"Academy Ruins":2 ,
	"Ghost Quarter":2 ,
	"Snapcaster Mage":1 ,
	"Elesh Norn, Grand Cenobite":1 ,
	"Serum Visions":4 ,
	"Path to Exile":4 ,
	"Spell Snare":2 ,
	"Muddle the Mixture":3 ,
	"Thopter Foundry":4 ,
	"Sword of the Meek":3 ,
	"Oblivion Ring":1 ,
	"Detention Sphere":1 ,
	"Talisman of Progress":2 ,
	"Thirst for Knowledge":4 ,
	"Wrath of God":1 ,
	"Supreme Verdict":1 ,
	"Gifts Ungiven":3 ,
	"Unburial Rites":1 ,
	"Engineered Explosives":1 ,
},
side:{
	"Jace, Vryn's Prodigy":1 ,
	"Iona, Shield of Emeria":1 ,
	"Terastodon":1 ,
	"Dispel":2 ,
	"Negate":1 ,
	"Hurkyl's Recall":1 ,
	"Disenchant":1 ,
	"Sunlance":1 ,
	"Celestial Purge":1 ,
	"Timely Reinforcements":1 ,
	"Rest for the Weary":1 ,
	"Gut Shot":1 ,
	"Supreme Verdict":1 ,
	"Wheel of Sun and Moon":1 ,
},
}
