{main:{
	"Delver of Secrets":4 ,
	"Gurmag Angler":2 ,
	"Snapcaster Mage":4 ,
	"Tasigur, the Golden Fang":2 ,
	"Young Pyromancer":2 ,
	"Dispel":1 ,
	"Kolaghan's Command":2 ,
	"Lightning Bolt":4 ,
	"Magma Spray":1 ,
	"Mana Leak":2 ,
	"Spell Snare":2 ,
	"Stubborn Denial":1 ,
	"Terminate":3 ,
	"Thought Scour":4 ,
	"Dreadbore":1 ,
	"Gitaxian Probe":3 ,
	"Serum Visions":4 ,
	"Blood Crypt":1 ,
	"Bloodstained Mire":3 ,
	"Flooded Strand":3 ,
	"Island":2 ,
	"Mountain":1 ,
	"Polluted Delta":2 ,
	"Steam Vents":2 ,
	"Sulfur Falls":1 ,
	"Swamp":2 ,
	"Watery Grave":1 ,
	},
side:{
	"Ancestral Vision":3 ,
	"Anger of Gods":1 ,
	"Batterskull":1 ,
	"Blood Moon":1 ,
	"Crumble to Dust":1 ,
	"Grim Lavamancer":1 ,
	"Izzet Staticaster":1 ,
	"Magma Spray":1 ,
	"Pia and Kiran Nalaar":1 ,
	"Surgical Extraction":1 ,
	"Thoughtseiz":2 ,
	"Vandalblast":1 ,
}}
