{main:{
	"Aven Mindcensor":1, 
	"Leonin Arbiter":4, 
	"Thalia, Guardian of Thraben":3, 
	"Blade Splicer":2, 
	"Flickerwisp":4, 
	"Restoration Angel":4, 
	"Birds of Paradise":4, 
	"Thalia, Heretic Cathar":2, 
	"Kitchen Finks":2, 
	"Qasali Pridemage":2, 
	"Eternal Witness":1, 
	"Scavenging Ooze":2, 
	"Path to Exile":4, 
	"Aether Vial":4, 
	"Horizon Canopy":4, 
	"Temple Garden":4, 
	"Razorverge Thicket":4, 
	"Stirring Wildwood":2, 
	"Ghost Quarter":4, 
	"Gavony Township":2, 
	"Plains":1, 
	"Forest":1, 
},side:{
	"Stony Silence":2, 
	"Spellskite":2, 
	"Selfless Spirit":2, 
	"Pithing Needle":2, 
	"Burrenton Forge-Tender":2, 
	"Mirran Crusader":2, 
	"Rest in Peace":2, 
	"Sunlance":1, 
}}
