{
	main:{
		"primeval titan":4, 
		"sakura-tribe elder":4, 
		"prismatic omen":2, 
		"khalni hearth expedition":4, 
		"summoner's pact":2, 
		"explore":3, 
		"farseek":2, 
		"search for tomorrow":4, 
		"scapeshift":4, 
		"lightning bolt":4, 
		"forest":4, 
		"mountain":7, 
		"verdant catacombs":3, 
		"wooded foothills":4, 
		"valakut, the molten pinnacle":3, 
		"stomping ground":3, 
		"cinder glade":3, 
	},
	side:{
		"nature's claim":3, 
		"obstinate baloth":3, 
		"pithing needle":1, 
		"anger of the gods":3, 
		"commune with lava":2, 
		"ricochet trap":2, 
		"rending volley":1, 
	}
}
