{
	main:
	{
		'Inkmoth Nexus':4,
		'Vines of Vastwood':4,
		'Viridian Corrupter':1,
		'Glistener Elf':4,
		'Windswept Heath':4,
		'Become Immense':3,
		'Noble Hierarch':4,
		'Mutagenic Growth':4,
		'Blighted agent':4,
		'Might of Old Krosa':4,
		'Gitaxian Probe':4,
		'Breeding Pool':3,
		"Dismember":1,
		'Forest':3,
		'Spellskite':2,
		'Pendelhaven':2,
		'Wild Defiance':1,
		'Misty Rainforest':2,
		"Rancor":1,
		"Apostle's Blessing":1,
		'Slip Through Space':1,
		'Twisted Image':1,
		'Dryad Arbor':1,
		'Distortion Strike':1,
	},
	side:
	{
		"Grafdigger's Cage":2,
		'Viridian Corrupter':1,
		"Nature's Claim":2,
		'Dispel':2,
		"Spell Pierce":2,
		'Wild Defiance':1,
		"Ranger's Guile":2,
		"Kitchen Finks":2,
		"Apostle's Blessing":1,
	}
}
