{
	main:
	{
		'Blighted agent':4,
		'Might of Old Krosa':4,
		'Gitaxian Probe':4,
		'Windswept Heath':4,
		'Noble Hierarch':4,
		'Wild Defiance':1,
		'Glistener Elf':4,
		'Inkmoth Nexus':4,
		'Dryad Arbor':1,
		'Become Immense':3,
		'Pendelhaven':2,
		"Apostle's Blessing":2,
		"Rancor":2,
		'Breeding Pool':3,
		'Forest':2,
		'Vines of Vastwood':4,
		'Spellskite':1,
		'Viridian Corrupter':1,
		"Dismember":1,
		'Distortion Strike':1,
		'Misty Rainforest':2,
		'Mutagenic Growth':4,
		"Ghost Quarter":1,
		'Slip Through Space':1,
	},
	side:
	{
		"Kitchen Finks":2,
		'Twisted Image':1,
		'Dismember':1,
		'Dispel':2,
		"Spell Pierce":2,
		'Wild Defiance':1,
		"Nature's Claim":2,
		'Viridian Corrupter':2,
		'Spellskite':1,
		"Thing in the Ice":2,
	}
}
