{
	main:
	{
		'Gitaxian Probe':4,
		'Glistener Elf':4,
		'Blighted agent':4,
		'Distortion Strike':1,
		'Might of Old Krosa':4,
		'Vines of Vastwood':4,
		'Slip Through Space':1,
		'Apostle\'s Blessing':2,
		'Mutagenic Growth':4,
		'Noble Hierarch':4,
		'Wild Defiance':1,
		'Become Immense':3,
		'Dryad Arbor':1,
		'Breeding Pool':3,
		'Forest':2,
		'Inkmoth Nexus':4,
		'Misty Rainforest':2,
		'Pendelhaven':2,
		'Temple Garden':1,
		'Windswept Heath':4,
		'Spellskite':2,
		'Path to Exile':1,
		'Twisted Image':1,
		'Vapor Snag':1,
	},
	side:
	{
			'Viridian Corrupter':2,
			'Echoing Truth':2,
			'Spell Pierce':3,
			'Dispel':2,
			'Path to Exile':1,
			'Dismember':1,
			'Spellskite':1,
			'Wild Defiance':1,
			'Ranger\'s Guile':2,
	}
}
