{
	main:{
		"Breeding Pool":2 ,
		"Cavern of Souls":2 ,
		"Forest":3 ,
		"Gavony Township":1 ,
		"Ghost Quarter":1 ,
		"Hallowed Fountain":1 ,
		"Horizon Canopy":1 ,
		"Misty Rainforest":3 ,
		"Plains":1 ,
		"Sejiri Steppe":1 ,
		"Stomping Ground":1 ,
		"Temple Garden":1 ,
		"Windswept Heath":4 ,
		"Birds of Paradise":3 ,
		"Noble Hierarch":4 ,
		"Qasali Pridemage":3 ,
		"Spellskite":2 ,
		"Jace, Vryn's Prodigy":1 ,
		"Scavenging Ooze":2 ,
		"Thalia, Heretic Cathar":1 ,
		"Geist of Saint Traft":3 ,
		"Spell Queller":3 ,
		"Knight of the Reliquary":4 ,
		"Eternal Witness":2 ,
		"Path to Exile":3 ,
		"Retreat to Coralhelm":3 ,
		"Collected Company":4 ,
	},
	side:{
		"Path to Exile":1 ,
		"Stony Silence":2 ,
		"Negate":2 ,
		"Rhox War Monk":2 ,
		"Eidolon of Rhetoric":2 ,
		"Spell Queller":1 ,
		"Izzet Staticaster":3 ,
		"Thrun, the Last Troll":2 ,
	}
}
