{
	main:{
		'Windswept Heath':4,
		'Wooded Foothills':3,
		'Misty Rainforest':1,
		'Dryad Arbor':1,
		'Forest':2,
		'Plains':1,
		'Mountain':1,
		'Hallowed Fountain':1,
		'Breeding Pool':2,
		'Stomping Ground':2,
		'Gavony Township':1,
		'Ghost Quarter':1,
		'Seijiri Steppe':1,
		'Horizon Canopy':1,
		'Sacred Foundry':1,
		'Birds of Paradise':4,
		'Noble Hierarch':2,
		'Wall of Roots':3,
		'Scryb Ranger':1,
		'Knight of the Reliquary':4,
		'Spike Feeder':1,
		'Scavenging Ooze':1,
		'Restoration Angel':3,
		'Kiki-jiki, Mirror Breaker':1,
		'Archangel of Thune':1,
		'Eternal Witness':2,
		'Spellskite':1,
		'Pia and Kiran Naalar':2,
		'Reclamation Sage':1,
		'Courser of Kruphix':1,
		'Retreat to Coralhelm':3,
		'Chord of Calling':4,
		'Path to Exile':4,
	},
	side:{
		'Kor Firewalker':1,
		'Negate':2,
		'Izzet Staticaster':2,
		'Flashfreeze':1,
		'Eidolon of Rethoric':1,
		'Qasali Pridemage':1,
		'Avalanche Riders':1,
		'Stony Silence':2,
		'Kataki, War\'s Wage':1,
		'Ancient Grudge':1,
		'Wear // Tear':1,
		'Keranos, God of Storms':3,
	}
}
