{
	main:{
		'Delver of Secrets':4,
		"Goblin Guide":4,
		"Young Pyromancer":3 ,
		'Snapcaster Mage':2,
		"Vendilion Clique":1,
		'Lightning Bolt':4,
		"Boros Charm":4,
		'Remand':4,
		"Lightning Helix":3,
		"Electrolyze":1,
		'Serum Visions':4,
		"Lava Spike":4,
		"Gitaxian Probe":3 ,
		"Seachrome Coast":3,
		'Sulfur Falls':1,
		"Clifftop Retreat":1,
		"Sacred Foundry":1,
		'Steam Vents':2,
		"Hallowed Fountain":2,
		'Island':1,
		"Mountain":1,
		"Plains":1,
		"Flooded Strand":3,
		'Scalding Tarn':3,
		"Arid Mesa":1,
	},
	side:{
		"Path to Exile":3,
		"Engineered Explosives":2,
		"Izzet Staticaster":1 ,
		"Wear // Tear":2,
		"Pithing Needle":2,
		"Stony Silence":1,
		'Dispel':2,
		'Negate':2,
	}
}
