{
	main:{
		"Snapcaster Mage":4 ,
		"Path to Exile":4 ,
		"Lightning Bolt":4 ,
		"Lightning Helix":3 ,
		"Electrolyze":3 ,
		"Sphinx's Revelation":1 ,
		"Think Twice":1 ,
		"Cryptic Command":3 ,
		"Remand":2 ,
		"Mana Leak":3 ,
		"Spell Snare":2 ,
		"Ancestral Vision":4 ,
		"Ajani Vengeant":1 ,
		"Gideon Jura":1 ,
		"Arid Mesa":1 ,
		"Desolate Lighthouse":1 ,
		"Mountain":1 ,
		"Plains":1 ,
		"Sacred Foundry":1 ,
		"Hallowed Fountain":2 ,
		"Island":2 ,
		"Ghost Quarter":2 ,
		"Sulfur Falls":2 ,
		"Steam Vents":2 ,
		"Scalding Tarn":3 ,
		"Flooded Strand":3 ,
		"Celestial Colonnade":4 ,
	},
	side:{
		"Supreme Verdict":1 ,
		"Wrath of God":1 ,
		"Timely Reinforcements":1 ,
		"Izzet Staticaster":1 ,
		"Negate":2 ,
		"Dispel":1 ,
		"Wear // Tear":2 ,
		"Stony Silence":1 ,
		"Rest in Peace":1 ,
		"Batterskull":1 ,
		"Crumble to Dust":2 ,
		"Elspeth, Champion of the Sun":1 ,
	},
}
