{
	main:{
		"Snapcaster Mage":3 ,
		"Geist of Saint Traft":3 ,
		"Vendilion Clique":1 ,
		"Pia and Kiran Nalaar":1 ,
		"Restoraion Angel":1 ,
		"Archangel Avacyn":1 ,

		"Lightning Bolt":4 ,
		"Path to Exile":4 ,
		"Serum Visions":4 ,
		"Spell Snare":2 ,
		"Lightning Helix":3 ,
		"Mana Leak":3 ,
		"Remand":3 ,
		"Electrolyze":2 ,
		"Cryptic Command":2 ,

		"Celestial Colonnade":4 ,
		"Arid Mesa":4 ,
		"Flooded Strand":3 ,
		"Island":2 ,
		"Mountain":1 ,
		"Plains":1 ,
		"Steam Vents":2 ,
		"Hallowed Fountain":2 ,
		"Sacred Foundry":1 ,
		"Sulfur Falls":1 ,
		"Desolate Lighthouse":1 ,
		"Tectonic Edge":1,
	},
	side:{
		"Engineered Explosives":1 ,
		"Dispel":1 ,
		"Wear // Tear":2 ,
		"Celestial Purge":1 ,
		"Negate":1 ,
		"Rest in Peace":2 ,
		"Stony Silence":2 ,
		"Anger of the Gods":2 ,
		"Counterflux":1 ,
		"Timely Reinforcements":1 ,
		"Crumble to Dust":1 ,
	},
}
