{
	main:{
		"Emrakul, the Aeons Torn":1, 
		"Snapcaster Mage":4, 
		"Vendilion Clique":1, 
		"Serum Visions":4, 
		"Supreme Verdict":1, 
		"Cryptic Command":2, 
		"Electrolyze":1, 
		"Lightning Bolt":4, 
		"Lightning Helix":2, 
		"Logic Knot":2, 
		"Path to Exile":4, 
		"Remand":2, 
		"Spell Snare":2, 
		"Sphinx's Revelation":1, 
		"Batterskull":1, 
		"Nahiri, the Harbinger":4, 
		"Celestial Colonnade":4, 
		"Flooded Strand":4, 
		"Ghost Quarter":1, 
		"Glacial Fortress":1, 
		"Hallowed Fountain":2, 
		"Island":2, 
		"Mountain":1, 
		"Plains":1, 
		"Sacred Foundry":1, 
		"Polluted Delta":3, 
		"Misty Rainforest":1, 
		"Steam Vents":2, 
		"Sulfur Falls":1, 
	},
	side:{
		"Anger of the Gods":1, 
		"Blessed Alliance":1, 
		"Counterflux":1, 
		"Crumble to Dust":2, 
		"Dispel":1, 
		"Izzet Staticaster":1, 
		"Keranos, God of Storms":1, 
		"Negate":1, 
		"Rest in Peace":1, 
		"Stony Silence":2, 
		"Supreme Verdict":1, 
		"Timely Reinforcements":1, 
		"Vendilion Clique":1, 
	},
}
