{
	main:{
		"Tarmogoyf":4,
		"Dark Confidant":4,
		"Scavenging Ooze":3,
		"Olivia Voldaren":1,
		"Huntmaster of the Fells":1 ,

		"Inquisition of Kozilek":4,
		"Thoughtseize":2,
		"Terminate":2,
		"Dreadbore":1 ,
		"Kolaghan's Command":2,
		"Liliana of the Veil":4,
		"Maelstrom Pulse":1,
		"Jund Charm":1 ,
		"Abrupt Decay":2,
		"Tarfire":1 ,
		"Lightning Bolt":4,

		"Raging Ravine":3,
		"Verdant Catacombs":2,
		"Wooded Foothills":2 ,
		"Bloodstained Mire":4 ,
		"Overgrown Tomb":1,
		"Blood Crypt":1,
		"Stomping Ground":1,
		"Swamp":2,
		"Forest":2,
		"Blackcleave Cliffs":4,
		"Ghost Quarter":1 ,
		"Twilight Mire":1 ,
	},
	side:{
		"Disfigure":1 ,
		"Duress":1,
		"Fulminator Mage":2,
		"Crumble to Dust":1 ,
		"Languish":1 ,
		"Anger of the Gods":1 ,
		"Slaughter Games":1 ,
		"Painful Truths":1 ,
		"Grafdigger's Cage":2 ,
		"Obstinate Baloth":1 ,
		"Pulse of Murasa":1 ,
		"Golgari Charm":1 ,
		"Unravel the aether":1 ,
	}
}
