{
	main:{
		"Scavenging Ooze":2, 
		"Tarmogoyf":4, 
		"Dark Confidant":4, 
		"Kalitas, Traitor of Ghet":1, 
		"Slaughter Pact":1, 
		"Kolaghan's Command":2, 
		"Abrupt Decay":2, 
		"Terminate":2, 
		"Ligthning Bolt":4, 
		"Anger of the Gods":1, 
		"Maelstrom Pulse":2, 
		"Dreadbore":1, 
		"Thoughtseize":2, 
		"Inquisition of Kozilek":4, 
		"Liliana of the Veil":3, 
		"Wooded Foothills":4, 
		"Bloodstained Mire":4, 
		"Verdant Catacombs":1, 
		"Raging Ravine":3, 
		"Treetop Village":1, 
		"Blackcleave Cliffs":4, 
		"Overgrown Tomb":1, 
		"Stomping Ground":1, 
		"Blood Crypt":1, 
		"Twilight Mire":1, 
		"Swamp":2, 
		"Forest":1, 
	},
	side:{
		"Night Soul's Betrayal":1, 
		"Slaughter Games":1, 
		"Ancient Grudge":1, 
		"Grafdigger's Cage":1, 
		"Duress":1, 
		"Kitchen Finks":3, 
		"Fulminator Mage":3, 
		"Anger of the Gods":2, 
		"Chandra, Torch of Defiance":1, 
		"Lost Legacy":1, 
	}
}
