{
	main:{
			"Grim Lavamancer":1 ,
			"Kalitas, Traitor of Ghet":1 ,
			"Scavenging Ooze":2 ,
			"Dark Confidant":4 ,
			"Tarmogoyf":4 ,
			"Kolaghan's Command":1 ,
			"Slaughter Pact":1 ,
			"Abrupt Decay":2 ,
			"Terminate":2 ,
			"Lightning Bolt":4 ,
			"Forked Bolt":2 ,
			"Maelstrom Pulse":2 ,
			"Thoughtseize":2 ,
			"Inquisition of Kozilec":4 ,
			"Arlin Kord":1 ,
			"Liliana of the Veil":3 ,
			"Blood Crypt":1 ,
			"Stomping Ground":1 ,
			"Twilight Mire":1 ,
			"Wooded Foothills":1 ,
			"Forest":1 ,
			"Overgrown Tomb":2 ,
			"Swamp":1 ,
			"Bloodstained Mire":4 ,
			"Raging Ravine":3 ,
			"Blackcleave Cliffs":4 ,
			"Verdant Catacombs":4 ,
			"Mountain":1 ,
	},
	side:{
		"Molten Rain":2 ,
		"Kitchen Finks ":2 ,
		"Ancient Grudge ":2 ,
		"Feed the Clan":2 ,
		"Golgari Charm":2 ,
		"Damnation ":1 ,
		"Dreadbore":2 ,
		"Anger of the Gods":2 ,
	}
}
