{
	main:{
		'Mountain':1,
		'Swamp':1,
		'Forest':1,
		'Treetop Village':2,
		'Wooded Foothills':3,
		'Bloodstained Mire':3,
		'Raging Ravine':2,
		"Blackcleave Cliffs":4,
		"Stomping Ground":1,
		"Blood Crypt":2,
		"Overgrown Tomb":2,
		"Kitchen Finks":2,
		"Eternal Witness":2,
		"Scavenging Ooze":2,
		"Olivia Voldaren":2,
		"Kalitas, Traitor of Ghet":2,
		"Tarmogoyf":3,
		"Thoughtseize":2,
		"Inquisition of Kozilek":4,
		"Arlinn Kord":1,
		"Liliana of the Veil":4,
		"Maelstrom Pulse":1,
		"Kozilek's Return":1,
		"Terminate":3,
		"Kolaghan's Command":2,
		"Abrupt Decay":3,
		"Lightning Bolt":4,
	},
	side:{
		'Rain of Gore':1,
		'Slaughter Games':1,
		'Relic of Progenitus':2,
		'Surgical Extraction':2,
		'Pithing Needle':2,
		'Languish':2,
		'Fulminator Mage':3,
		'Crumble to Dust':2,
	}
}
