{
	main:{
		'Windswept Heath':4,
		'Wooded Foothills':4,
		'Forest':2,
		'Stomping Ground':2,
		'Overgrown Tomb':2,
		'Plains':1,
		'Mountain':1,
		'Sacred Foundry':1,
		'Razorveige Thicket':1,
		'Temple Garden':1,
		'Raging Ravine':1,
		'Sunpetal Grove':1,
		'Horizon Canopy':1,
		'Ghost Quarter':1,
		'Fire-Lit Thicket':1,
		'Big Game Hunter':1,
		'Kiki-jiki, Mirror Breaker':1,
		'Scavenging Ooze':1,
		'Qasali Pridemage':1,
		'Spellskite':1,
		'Orzhov Pontiff':1,
		'Lone Missionary':1,
		'Reveillark':1,
		'Eternal Witness':2,
		'Pia and Kiran Naalar':2,
		'Restoration Angel':3,
		'Wall of Roots':3,
		'Wall of Omens':3,
		'Voice of Resurgence':3,
		'Birds of Paradise':4,
		'Chord of Calling':3,
		'Path to Exile':4,
		'Courser of Kruphix':2,
	},
	side:{
		'Phyrexian Revoker':1,
		'Fulminator Mage':2,
		'Stony Silence':2,
		'Spellskite':1,
		'Reclamation Sage':1,
		'Shriekmaw':1,
		'Eidolon of Rethoric':1,
		'Scavenging Ooze':1,
		'Sin collector':1,
		'Dismember':1,
		'Lightning Helix':3,
	}
}
