{main:{
	"Anafenza, the Foremost ":1, 
	"Spellskite":1, 
	"Birds of Paradise":4, 
	"Burrenton Forge-Tender":1, 
	"Eternal Witness":3, 
	"Orzhov Pontiff":1, 
	"Qasali Pridemage":1, 
	"Restoration Angel":3, 
	"Reveillark":1, 
	"Scavenging Ooze":2, 
	"Selfless Spirit":1, 
	"Voice of Resurgence":3, 
	"Wall of Roots":2, 
	"Kiki-Jiki, Mirror Breaker":1, 
	"Pia and Kiran Nalaar":1, 
	"Noble Hierarch":1, 
	"Chord of Calling":4, 
	"Lightning Bolt":3, 
	"Path to Exile":4, 
	"Eldritch Evolution":1, 
	"Mountain":1, 
	"Plains":1, 
	"Forest":2, 
	"Windswept Heat":3, 
	"Misty Rainforest":3, 
	"Copperline Gorge":1, 
	"Razorverge Thicket":2, 
	"Temple Garden":2, 
	"Overgrown Tomb":1, 
	"Sacred Foundry":1, 
	"Stomping Ground":3, 
	"Marsh Flats":1, 
	"Scalding Tarn ":1, 
},side:{
	"Surgical Extraction":2, 
	"Slaughter Games":2, 
	"Reclamation Sage":1, 
	"Ghostly Prison":3, 
	"Thragtusk":1, 
	"Eidolon of Rhetoric":1, 
	"Avalanche Riders":1, 
	"Melira, Sylvok Outcast":1, 
	"Thrun, the Last Troll ":1, 
	"Aven Mindcensor":1, 
	"Kataki, War's Wage ":1, 
}}
