{main:{
	"Monastery Swiftspear":3, 
	"Kiln Fiend":4, 
	"Thing in the Ice":4, 
	"Bedlam Reveler":2, 
	"Faithless Looting":2, 
	"Gitaxian Probe":4, 
	"Lightning Bolt":4, 
	"Mutagenic Growth":4, 
	"Serum Visions":4, 
	"Sleight of Hand":2, 
	"Apostle's Blessing":2, 
	"Manamorphose":4, 
	"Temur Battlerage":4, 
	"Flooded Strand":1, 
	"Scalding Tarn":3, 
	"Spirebluff Canal":3, 
	"Steam Vents":4, 
	"Sulfur Falls":3, 
	"Mountain":1, 
	"Island":2, 
},side:{
	"Dispel":2, 
	"Grafdigger's Cage":2, 
	"Vandalblast":2, 
	"Vapor Snag":2, 
	"Swan Song":2, 
	"Young Pyromancer":2, 
	"Blood Moon":2, 
	"Bedlam Reveler":1, 
}}
