{
	main:{
		'Academy Ruins':2,
		'Blackcleave Cliffs':2,
		'Copperline Gorge':1,
		'Forest':1,
		'Ghost Quarter':2,
		'Glimmervoid':4,
		'Llanowar Wastes':4,
		'Tendo Ice Bridge':1,
		'Spellskite':3,
		'Mox Opal':4,
		'Ancient Stirrings':4,
		'Codex Shredder':4,
		'Ghoulcaller\'s Bell':4,
		'Inquisition of Kozilek':4,
		'Lantern of Insight':4,
		'Pithing Needle':3,
		'Pyrite Spellbomb':1,
		'Surgical Extraction':2,
		'Thoughtseize':3,
		'Abrupt Decay':2,
		'Infernal Tutor':1,
		'Ensnaring Bridge':4,
		'Ghirapur Aether Grid':4,
	},
	side:{
		'Welding Jar':2,
		'Grafdigger\'s Cage':1,
		'Nature\'s Claim':3,
		'Pyroclasm':2,
		'Sun Droplet':3,
		'Leyline of Sanctity':4,
	}
}
