{
	main:{
		"Glint-Nest Crane":2,	
		"Spellskite":1,	
		"Ancient Stirrings":4,	
		"Inquisition of Kozilek":4,	
		"Surgical Extraction":2,	
		"Thoughtseize":2,	
		"Abrupt Decay":3,	
		"Collective Brutality":1,	
		"Mox Opal":4,	
		"Codex Shredder":4,	
		"Ghoulcaller's Bell":3,	
		"Lantern of Insight":4,	
		"Pithing Needle":3,	
		"Pyxis of Pandemonium":1,	
		"Ensnaring Bridge":4,	
		"Academy Ruins":2,	
		"Tendo Ice Bridge":1,	
		"Blooming Marsh":4,	
		"Botanical Sanctum":1,	
		"Darkslick Shores":2,	
		"Forest":1,	
		"Ghost Quarter":1,	
		"Glimmervoid":4,	
		"Inventors' Fair":2,	
	},
	side:{
		"Welding Jar":2,	
		"Grafdigger's Cage":1,	
		"Nature's Claim":1,	
		"Seal of Primordium":1,	
		"Surgical Extraction":2,	
		"Thoughtseize":1,	
		"Collective Brutality":1,	
		"Spellskite":1,	
		"Crucible of Worlds":1,	
		"Leyline of Sanctity":2,	
		"Sun Droplet":1,	
		"Witchbane Orb":1,	
	}
}
