{main:{
	"Caves of Koilos":3, 
	"Isolated Chapel":4, 
	"ghost quarter":2, 
	"Plains":2, 
	"Shambling Vent":2, 
	"Swamp":4, 
	"Urborg, Tomb of Yawgmoth":1, 
	"Vault of the Archangel":1, 
	"Blood Artist":4, 
	"Bloodthrone Vampire":1, 
	"Doomed Traveler":4, 
	"Geralf's Messenger":2, 
	"Gravecrawler":4, 
	"Pawn of Ulamog":2, 
	"Tidehollow Sculler":3, 
	"Viscera Seer":3, 
	"Zulaport Cutthroat":3, 
	"Athreos, God of Passage":1, 
	"Blasting Station":2, 
	"Lingering Souls":3, 
	"Path to Exile":2, 
	"Phyrexian Arena":1, 
	"Rally the Ancestors":2, 
	"Tragic Slip":2, 
	"Zealous Persecution":2, 
},
side:{
	"Disenchant":4, 
	"Nihil Spellbomb":3, 
	"Tragic Slip":2, 
	"tidehollow sculler":1, 
	"mana tithe":3, 
	"damnation":2, 
}}
