{main:{
	"Mountain":16 ,
	"Teetering Peaks":2 ,
	"Vexing Devil":4 ,
	"Spark elemental":4 ,
	"Monastery Swiftspear":4 ,
	"Eidolon of the Great Revel":3 ,
	"Keldon marauders":2 ,
	"Lightning Bolt":4 ,
	"Lava Spike":4 ,
	"Rift Bolt":4 ,
	"Forked Bolt":4 ,
	"Skullcrack":4 ,
	"Searing Blaze":3 ,
	"Thunderous Wrath":1 ,
	"Shard Volley":2 ,
},
side:{}}
