{
	main:{
		"Verdant Catacombs":2, 
		"Marsh Flats":4, 
		"Misty Rainforest":1, 
		"Overgrown Tomb":2, 
		"Godless Shrine":1, 
		"Temple Garden":1, 
		"Stirring Wildwood":3, 
		"Wooden Bastion":1, 
		"Urborg, Tomb of Yawgmoth":2, 
		"Ghost Quarter":3, 
		"Swamp":1, 
		"Forest":1, 
		"Plains":1, 
		"Birds of Paradise":3, 
		"Dark Confidant":4, 
		"Tarmogoyf":3, 
		"Thrun, the Last Troll":2, 
		"Loxodon Smiter":2, 
		"Siege Rhino":2, 
		"Vampire Hexmage":3, 
		"Liliana of the Veil":3, 
		"Lingering Souls":4, 
		"Thoughtseize":3, 
		"Inquisition of Kozilek":3, 
		"Abrupt Decay":2, 
		"Maelstrom Pulse":2, 
		"Path to Exile":2, 
	},
	side:{
		"Nihil Spellbomb":3, 
		"Stony Silence":3, 
		"Wrath of God":2, 
		"Abrupt Decay":2, 
		"Path to Exile":2, 
		"Extirpate":3, 
	}
}
