{
	main:{
		'Stomping Ground':1,
		'Blood Crypt':1,
		'Overgrown Tomb':1,
		'Forest':1,
		'Swamp':1,
		'Verdant Catacombs':1,
		'Bloodstained Mire':1,
		'Blackcleave Cliffs':4,
		'Copperline Gorge':4,
		'Forbidden Orchard':4,
		'Living End':3,
		'Violent Outburst':4,
		'Demonic Dread':4,
		'Beast Within':2,
		'Dryad Arbor':1,
		'Simian Spirit Guide':3,
		'Street Wraith':4,
		'Fulminator Mage':4,
		'Deadshot Minotaur':4,
		'Monstruous Carabid':4,
		'Architects of Will':2,
		'Avalanche Riders':2,
		'Pale Recluse':4,
		'Shriekmaw':1,
	},
	side:{
		'Ingot Chewer':3,
		'Brindle Boar':3,
		'Jund Charm':2,
		'Slaughter Games':3,
		'Faerie Macabre':2,
		'Beast Within':2,
	}
}
