{
	main:{
		'Faerie Macabre':2,
		'Street Wraith':4,
		'Architects of Will':4,
		'Deadshot Minotaur':4,
		'Monstruous Carabid':4,
		"Jungle Weaver":2,
		'Simian Spirit Guide':4,
		'Fulminator Mage':4,
		'Beast Within':3,
		'Demonic Dread':4,
		'Violent Outburst':4,
		'Living End':3,
		'Bloodstained Mire':4,
		"Wooded Foothills":1,
		'Overgrown Tomb':1,
		'Blood Crypt':1,
		'Stomping Ground':1,
		"Steam Vents":1,
		"Copperline Gorge":4,
		'Blackcleave Cliffs':4,
		'Swamp':1,
		'Forest':1,
	},
	side:{
		'Ingot Chewer':4,
		'Shriekmaw':3,
		"Ricochet Trap":3,
		"Anger of the Gods":2,
		'Slaughter Games':3,
	}
}
