{
	main:{
		'Shambling Vent':4,
		'Lavaclaw Reaches':1,
		'Vault of the Archangel':1,
		'Swamp':2,
		'Mountain':1,
		'Plains':1,
		'Godless Shrine':1,
		'Blood Crypt':1,
		'Sacred Foundry':1,
		'Blackcleave Cliffs':3,
		'Bloodstained Mire':4,
		'Arid Mesa':3,
		'Dark Confidant':4,
		'Abbot of Keral Keep':3,
		'Grim Lavamancer':1,
		'Olivia Voldaren':1,
		'Inquisition of Kozilek':4,
		'Thoughtseize':2,
		'Lightning Bolt':4,
		'Lightning Helix':2,
		'Zealous Persecution':1,
		'Path to Exile':4,
		'Terminate':1,
		'Lingering Souls':4,
		'Kolaghan\'s Command':2,
		'Liliana of the Veil':3,
		'Ajani Vengeant':3,
	},
	side:{
		'Crackling Doom':1,
		'Wear // Tear':1,
		'Rakdos Charm':1,
		'Timely Reinforcements':1,
		'Celestial Purge':1,
		'Graffdigger\'s Cage':1,
		'Stony Silence':2,
		'Wrath of God':1,
		'Flaying Tendrils':1,
		'Curse of Death\'s Hold':1,
		'Fulminator Mage':2,
		'Blood Baron of Vizkopa':1,
	}
}
