{
	main:{
		'Path to Exile':3,
		'Lightning Bolt':4,
		'Thoughtseize':2,
		'Inquisition of Kozilek':3,
		'Terminate':3,
		'Lightning Helix':4,
		'Painful Truths':2,
		"Kolaghan's Command":2,
		'Liliana of the Veil':4,
		'Ajani Vengeant':2,
		'Lingering Souls':4,
		'Kalitas, Traitor of Ghet':3,
		'Olivia Voldaren':2,
		'Bloodstained Mire':3,
		'Shambling Vent':3,
		'Blackcleave Cliffs':4,
		'Blood Crypt':2,
		'Plains':1,
		'Sacred Foundry':1,
		'Tectonic Edge':1,
		'Godless Shrine':2,
		'Mountain':1,
		'Windswept Heath':3,
	},
	side:{
		'Path to Exile':1,
		'Pia and Kiran Nalaar':2,
		'Mind Rot':1,
		'Wrath of God':1,
		'Declaration in Stone':2,
		'Fulminator Mage':3,
		'Inquisition of Kozilek':1,
		'Anguished Unmaking':2,
	}
}
