{
	main:{
		'Plains':1,
		'Forest':2,
		'Swamp':1,
		'Temple Garden':2,
		'Sacred Foundry':1,
		'Godless Shrine':1,
		'Overgrown Tomb':1,
		'Gavony Township':2,
		'Flooded Strand':2,
		'Windswept Heath':4,
		'Sunpetal Grove':2,
		'Isolated Chapel':1,
		'Marsh Flats':1,

		'Viscera Seer':3,
		'Birds of Paradise':4,
		'Avacyn\'s Pilgrim':2,
		'Wall of Roots':2,
		'Anafenza, Kin-Tree Spirit':2,
		'Melira, Sylvok Outcast':2,
		'Spellskite':1,
		'Scavenging Ooze':1,
		'Qasali Pridemage':1,
		'Eidolon of the Rhetoric':1,
		'Kitchen Finks':4,
		'Eternal Witness':3,
		'Chord of Calling':4,
		'Collected Company':4,
		'Path to Exile':2,
		'Restoration Angel':1,
		'Murderous Redcap':1,
	},
	side:{
		'Realm Razer':1,
		'Fiend Hunter':1,
		'Reveillark':1,
		'Sigarda, Host of Herons':2,
		'Kataki, War\'s Wage':2,
		'Eidolon of the Rhetoric':1,
		'Phyrexian Revoker':1,
		'Anguished Unmaking':1,
		'Sin Collector':3,
		'Crumble to dust':3,
	}
}
