{main:{
		"Birds Of Paradise":4, 
		"Noble Hierarch":3, 
		"Wall of Roots":1, 
		"Viscera Seer":3, 
		"Voice of Resurgence":2, 
		"Selfless Spirit":1, 
		"Anafenza, Kin-tree spirit":2, 
		"Melira, Sylvok Outcast":2, 
		"Qasali Pridemage":1, 
		"Scavenging Ooze":1, 
		"Kitchen Finks":4, 
		"Eternal Witness":2, 
		"Orzhov Pontiff":1, 
		"Spellskite":1, 
		"Murderous Redcap":1, 
		"Fiend Hunter":1, 
		"Chord of Calling":4, 
		"Collected Company":4, 
		"Windswept Heath":4, 
		"Verdant Catacombs":4, 
		"Temple Garden":2, 
		"Overgrown Tomb":2, 
		"Godless Shrine":1, 
		"Forest":2, 
		"Plains":1, 
		"Swamp":1, 
		"Horizon Canopy":2, 
		"Gavony Township":3, 
},side:{
		"Fulminator Mage":3, 
		"Path to Exile":2, 
		"Thoughtseize":3, 
		"Sin Collector":2, 
		"Reclamation Sage":1, 
		"Kataki, War's Wage":1, 
		"Abrupt Decay":2, 
		"Thrun, The Last Troll":1, 
}}
