{
	main:{
		'Forest':3,
		'Plains':1,
		'Gavony Township':2,
		'Flooded Strand':2,
		'Overgrown Tomb':1,
		'Isolated Chapel':1,
		'Godless Shrine':1,
		'Misty Rainforest':1,
		'Swamp':1,
		'Marsh Flats':1,
		'Sacred Foundry':1,
		'Sunpetal Grove':2,
		'Windswept Heath':2,
		'Temple Garden':2,
		'Birds of Paradise':4,
		'Avacyn\'s Pilgrim':4,
		'Viscera Seer':3,
		'Scavenging Ooze':2,
		'Qasali Pridemage':1,
		'Wall of Roots':3,
		'Anafenza, Kin-Tree Spirit':2,
		'Melira, Sylvok Outcast':2,
		'Spellskite':1,
		'Fiend Hunter':1,
		'Eidolon of the Rhetoric':1,
		'Kitchen Finks':4,
		'Eternal Witness':3,
		'Murderous Redcap':1,
		'Path to Exile':2,
		'Chord of Calling':4,
		'Collected Company':4,
	},
	side:{
		'Realm Razer':1,
		'Sin Collector':3,
		'Eidolon of the Rhetoric':1,
		'Shriekmaw':1,
		'Reclamation Sage':2,
		'Fiend Hunter':1,
		'Phyrexian Revoker':1,
		'Restoration Angel':1,
		'Reveillark':1,
		'Kataki, War\'s Wage':2,
		'Sigarda, Host of Herons':2,
	}
}
