{
	main:{
		'Evolving Wilds':4,
		'Llanowar Wastes':1,
		'Brushland':1,
		'Sandsteppel Citadel':2,
		'Scoured Barrens':1,
		'Stirring Wildwood':1,
		'Tectonic Edge':1,
		'Forest':4,
		'Plains':4,
		'Swamp':5,
		'Catacomb Sifter':4,
		'Secure the Wastes':3,
		'Go for the Throat':2,
		'Raise the Alarm':4,
		'Intangible Virtue':4,
		'Midnight Haunting':2,
		'Doom Blade':3,
		'Smother':1,
		'Murderous Cut':2,
		'Loxodon Hierarch':2,
		'Garruk Wildspeaker':1,
		'Tasigur, the Golden Fang':1,
		'Ultimate Price':1,
		'Elspeth, Sun\'s Champion':1,
		'Abzan Charm':1,
		'Read the Bones':2,
	},
	side:{
		'Duress':4,
		'Phyrexian Revoker':2,
		'Damping Matrix':2,
		'End Hostilities':2,
		'Foul-Tongue Invocation':1,
		'Sunlance':2,
		'Circle of Protection: Red':1,
		'Wurmcoil Engine':1,
		'Rest for the Weary':1,
	}
}
