{
	main:{
		"Flooded Strand":4 ,
		"Scalding Tarn":2 ,
		"Arid Mesa":1 ,
		"Island":3 ,
		"Plains":1 ,
		"Mountain":1 ,
		"Hallowed Fountain":2 ,
		"Steam Vents":2 ,
		"Sacred Foundry":1 ,
		"Sulfur Falls":1 ,
		"Celestial Colonnade":3 ,
		"Ghost Quarter":2 ,
		"Desolated Lighthouse":1 ,
		"Serum Visions":4 ,
		"Path to Exile":4 ,
		"Lightning Bolt":4 ,
		"Spell Snare":2 ,
		"Mana Leak":3 ,
		"Remand":2 ,
		"Lightning Helix":2 ,
		"Snapcaster Mage":4 ,
		"Electrolyze":2 ,
		"Vendilion Clique":1 ,
		"Cryptic Command":2 ,
		"Supreme Verdict":1 ,
		"Nahiri, the Harbinger":4 ,
		"Emrakul, the Aeons Torn":1 ,
	},
	side:{
		"Dispel":2 ,
		"Negate":1 ,
		"Izzet Staticaster":1 ,
		"Spell Queller":2 ,
		"Celestial Purge":1 ,
		"Timely Reinforcements":2 ,
		"Wrath of God":1 ,
		"Anger of the Gods":1 ,
		"Engineered Explosives":1 ,
		"Crumble to Dust":2 ,
		"Wear//Tear":1 ,
	},
}
