{main:{
	"Arid Mesa":1, 
	"Flagstones of Trokair":4, 
	"Forest":1, 
	"Mountain":1, 
	"Plains":1, 
	"Sacred Foundry":2, 
	"Stomping Ground":3, 
	"Temple Garden":1, 
	"Windswept Heath":4, 
	"Wooded Foothills":4, 
	"Arbor Elf":4, 
	"Goblin Dark-Dwellers":1, 
	"Emrakul, the Aeons Torn":1, 
	"Lightning Bolt":4, 
	"Utopia Sprawl":4, 
	"Boom // Bust":4, 
	"Stone Rain":4, 
	"Beast Within":2, 
	"Anger of the Gods":3, 
	"Molten Rain":3, 
	"Ajani Vengeant":2, 
	"Nahiri, the Harbinger":4, 
	"Chandra, Torch of Defiance":1, 
	"Gideon Jura":1, 
},side:{
	"Blessed Alliance":1, 
	"Rest in Peace":2, 
	"Stony Silence":2, 
	"Ancient Grudge":1, 
	"Wear // Tear (Wear)":1, 
	"Timely Reinforcements":2, 
	"Boil":2, 
	"Wrath of God":2, 
	"Thrun, the Last Troll":2, 
}}
