{main:{
	"The Rack":4, 
	"Thoughtseize":4, 
	"Wrench Mind":4, 
	"Inquisition of Kozilek":4, 
	"Lightning Bolt":4, 
	"Dark Confidant":4, 
	"Shrieking Affliction":4, 
	"Blightning":4, 
	"Terminate":3, 
	"Kolaghan's Command":3, 
	"Grim Lavamancer":2, 
	"Blood Crypt":4, 
	"Bloodstained Mire":4, 
	"Wooded Foothills":2, 
	"Polluted Delta":2, 
	"Dragonskull Summit":2, 
	"Swamp":4, 
	"Mountain":2, 
},side:{
	"Monastery Swiftspear":4, 
	"Fulminator Mage":2, 
	"Surgical Extraction":2, 
	"Relic of Progenitus":2, 
	"Kalitas, Traitor of Ghet":2, 
	"Kolaghan's Command":1, 
	"Dismember":1, 
	"Tormod's Crypt":1, 
}}
