{
main:{
	"Arbor Elf":4 ,
	"Birds of Paradise":2 ,
	"Goblin Dark Dwellers":3 ,
	"Restoration Angel":3 ,
	"Eternal Witness":2 ,
	"Kiki-Jiki, Mirror Breaker":2 ,
	"Utopia Sprawl":4 ,
	"Stone Rain":4 ,
	"Molten Rain":2 ,
	"Boom // Bust":4 ,
	"Primal Command":3 ,
	"Lightning Helix":3 ,
	"Ajani Vengeant":1 ,
	"Windswept Heath":4 ,
	"Wooded Foothills":4 ,
	"Temple Garden":3 ,
	"Sacred Foundry":2 ,
	"Forest":2 ,
	"Mountain":1 ,
	"Flagstones of Trokair":4 ,
	"Stomping Ground":3 ,
},
side:{
	"Krosan Grip":1 ,
	"Stony Silence":2 ,
	"Feed the Clan":2 ,
	"Obstinate Baloth":2 ,
	"Thragtusk":1 ,
	"Relic of Progenitus":3 ,
	"Anger of the Gods":2 ,
	"Wrath of God":1 ,
},
}
