{main:{
	"Dismember":4, 
	"Funeral Charm":2, 
	"Inquisition of Kozilek":4, 
	"Liliana of the Veil":4, 
	"Mutavault":4, 
	"Raven's Crime":4, 
	"Shrieking Affliction":4, 
	"Smallpox":4, 
	"Swamp":15, 
	"The Rack":4, 
	"Thoughtseize":3, 
	"Tomb of Urami":1, 
	"Urborg, Tomb of Yawgmoth":4, 
	"Wrench Mind":3, 
},side:{
	"Asylum Visitor":2, 
	"Bile Blight":1, 
	"Deathmark":1, 
	"Disfigure":3, 
	"Extirpate":1, 
	"Flaying Tendrils":1, 
	"Illness in the Ranks":1, 
	"Leyline of the Void":3, 
	"Night of Souls' Betrayal":1, 
	"Relic of Progenitus":1, 
}}
