{main:{
	"Birds of Paradise":4, 
	"Viscera Seer":3, 
	"Avacyn's Pilgrim":2, 
	"Scavenging Ooze":2, 
	"Anafenza, Kin-Tree Spirit":2, 
	"Selfless Spirit":1, 
	"Qasali Pridemage":1, 
	"Melira, Sylvok Outcast":2, 
	"Wall of Roots":2, 
	"Tireless Tracker":2, 
	"Kitchen Finks":4, 
	"Eternal Witness":2, 
	"Fiend Hunter":1, 
	"Path to Exile":2, 
	"Murderous Redcap":1, 
	"Chord of Calling":3, 
	"Collected Company":4, 
	"Forest":2, 
	"Plains":1, 
	"Windswept Heath":4, 
	"Sunpetal Grove":2, 
	"Gavony Township":2, 
	"Marsh Flats":1, 
	"Isolated Chapel":1, 
	"Godless Shrine":1, 
	"Flooded Strand":2, 
	"Blooming Marsh":2, 
	"Overgrown Tomb":2, 
	"Temple Garden":2, 
},side:{
	"Pharika, God of Affliction":1, 
	"Sigarda, Host of Herons":1, 
	"Spellskite":1, 
	"Dismember":2, 
	"Courser of Kruphix":2, 
	"Distended Mindbender":2, 
	"Eidolon of Rhetoric":2, 
	"Orzhov Pontiff":1, 
	"Tidehollow Sculler":3, 
}}
