{
main:{
	"Kitchen Finks":4 ,
	"Anafenza, Kin-Tree Spirit":2 ,
	"Temple Garden":2 ,
	"Eternal Witness":3 ,
	"Viscera Seer":3 ,
	"Birds of Paradise":4 ,
	"Spellskite":1 ,
	"Path to Exile":2 ,
	"Wall of Roots":2 ,
	"Chord of Calling":4 ,
	"Sunpetal Grove":2 ,
	"Restoration Angel":1 ,
	"Forest":2 ,
	"Swamp":1 ,
	"Plains":1 ,
	"Gavony Township":2 ,
	"Isolated Chapel":1 ,
	"Flooded Strand":2 ,
	"Scavenging Ooze":2 ,
	"Collected Company":4 ,
	"Murderous Redcap":1 ,
	"Overgrown Tomb":1 ,
	"Windswept Heath":4 ,
	"Qasali Pridemage":1 ,
	"Sacred Foundry":1 ,
	"Avacyn's Pilgrim":2 ,
	"Marsh Flats":1 ,
	"Melira, Sylvok Outcast":2 ,
	"Fiend Hunter":1 ,
	"Godless Shrine":1 ,
},
side:{
	"Eidolon of Rhetoric":2 ,
	"Kataki, War's Wage":1 ,
	"Orzhov Pontiff":1 ,
	"Burrenton Forge-Tender":1 ,
	"Dismember":2 ,
	"Sigarda, Host of Herons":1 ,
	"Phyrexian Revoker":1 ,
	"Tidehollow Sculler":3 ,
	"Crumble to Dust":3 ,
}
}
