{
main:{
	'Godless Shrine':1,
	'Flooded Strand':2,
	'Sunpetal Grove':2,
	'Windswept Heath':4,
	'Sacred Foundry':1,
	'Marsh Flats':1,
	'Isolated Chapel':1,
	'Plains':1,
	'Overgrown Tomb':1,
	'Forest':2,
	'Temple Garden':2,
	'Gavony Township':2,
	'Swamp':1,

	'Viscera Seer':3,
	'Birds of Paradise':4,
	'Kitchen Finks':4,
	'Murderous Redcap':1,
	'Melira, Sylvok Outcast':2,
	'Scavenging Ooze':2,
	"Avacyn's Pilgrim":2,
	'Eternal Witness':3,
	'Anafenza, Kin-Tree Spirit':2,
	'Fiend Hunter':1,
	'Qasali Pridemage':1,
	'Wall of Roots':2,
	'Spellskite':1,
	'Restoration Angel':1,
	'Chord of Calling':4,
	'Path to Exile':2,
	'Collected Company':4,

},
side:{
	'Eidolon of Rhetoric':2,
	'Phyrexian Revoker':1,
	"Fiend Hunter":1,
	"Crumble to Dust":2,
	'Kataki, War\'s Wage':1,
	'Dismember':2,
	"Sigarda, Host of Herons":1,
	'Sin Collector':3,
	'Reclamation Sage':1,
	"Rally the Ancestors":1,
}
}
