{
	main:{
		"Greater Gargadon":4,
		"Simian Spirit Guide":4,
		"Beast Within":2,
		"Dismember":2,
		"Violent Outburst":4,
		"Restore Balance":3,
		"Thassa, God of the Sea":1,
		"Mogis, God of Slaughter":1,
		"March of the Machines":3,
		"Ardent Plea":4,
		"Jace, Memory Adept":1,
		"Ajani Vengeant":2,
		"Mistvein Borderpost":4,
		"Fieldmist Borderpost":4,
		"Firewild Borderpost":4,
		"Wildfield Borderpost":4,
		"Forest":1,
		"Plains":1,
		"Swamp":1,
		"Mountain":2,
		"Island":2,
		"Evolving Wilds":2,
		"Terramorphic Expanse":4,
	},
	side:{
		"Bow of Nylea":1,
		"Monastery Siege":1,
		"Ghirapur Æther Grid":1,
		"Witchbane Orb":1,
		"Bring to Light":1,
		"Ricochet Trap":2,
		"Creeping Corrosion":1,
		"Slagstorm":1,
		"Ghostly Prison":2,
		"Pulse of the Fields":2,
		"Detention Sphere":1,
		"Batterskull":1,
	}
}
