{
main:{
	"Urza's Tower":4,
	"Urza's Mine":4,
	"Urza's Power Plant":4,
	"Sanctum of Ugin":1, 
	"Forest":1, 
	"Ghost Quarter":2, 
	"Grove of the Burnwillows":1, 
	"Karplusan Forest":3, 
	"Thought-Knot Seer":1, 
	"Spellskite":1, 
	"World Breaker":2, 
	"Wurmcoil Engine":3, 
	"Ulamog, the Ceaseless Hunger":1, 
	"Ancient Stirrings":4, 
	"Sylvan Scrying":4, 
	"Expedition Map":4, 
	"Chromatic Sphere":4, 
	"Chromatic Star":4, 
	"Karn Liberated":4, 
	"Ugin, the Spirit Dragon":2, 
	"Oblivion Stone":3, 
	"Firespout":3, 
},
side:{
	"Chalice of the Void":1,
	"Sudden Shock":1, 
	"Spellskite":1, 
	"Pulse of Murasa":1, 
	"Nature's Claim":3, 
	"Crucible of Worlds":1, 
	"Thragtusk":1, 
	"Thought-Knot Seer":1, 
	"Relic of Progenitus":2, 
	"Warping Wail":2, 
}
}
