{
	main:{
		'Delver of Secrets':4,
		'Snapcaster Mage':3,
		'Tarmogoyf':3,
		'Hooting Mandrils':4,
		'Dispel':1,
		'Gitaxian Probe':4,
		'Lightning Bolt':4,
		'Serum Visions':4,
		'Spell Snare':2,
		'Stubborn Denial':3,
		'Thought Scour':4,
		'Mana Leak':3,
		'Remand':1,
		'Electrolyze':1,

		'Breeding Pool':1,
		'Desolate Lighthouse':1,
		'Forest':1,
		'Island':3,
		'Misty Rainforest':4,
		'Mountain':1,
		'Polluted Delta':1,
		'Steam Vents':2,
		'Stomping Ground':1,
		'Wooded Foothills':4,
	},
	side:{
		'Engineered Explosives':1,
		'Grafdigger\'s Cage':1,
		'Natural State':2,
		'Ancient Grudge':2,
		'Feed the Clan':2,
		'Pyroclasm':2,
		'Anger of the Gods':1,
		'Blood Moon':3,
	}
}
