{
	main:{
		'Wooded Foothills':1,
		'Bloodstained Mire':4,
		"Verdant Catacombs":3,
		"Windswept Heath":4,
		"Blood Crypt":1,
		"Godless Shrine":1,
		"Overgrown Tomb":1,
		"Sacred Foundry":1,
		"Stomping Ground":1,
		"Death's Shadow":4,
		"Monastery Swiftspear":4,
		"Steppe Lynx":2,
		"Wild Nacatl":4,
		"Street Wraith":4,
		"Tarmogoyf":1,
		"Become Immense":3,
		"Temur Battle Rage":4,
		"Thoughtseize":3,
		"Mutagenic Growth":4,
		"Gitaxian Probe":4,
		"Lightning Bolt":2,
		"Mishra's Bauble":4,
	},
	side:{
		'Ancient Grudge':1,
		'Dismember':1,
		'Forest':1,
		'Hooting Mandrils':2,
		'Inquisition of Kozilek':2,
		'Lightning Helix':1,
		'Natural State':1,
		'Phyrexian Unlife':1,
		'Ranger of Eos':1,
		'Pyroclasm':1,
		'Stony Silence':1,
		"Grafdigger's Cage":1,
	}
}
