
{
main:{
			 'Temple Garden':1,
			 'Godless Shrine':1,
			 'Marsh Flats':1,
			 'Razorverge Thicket':2,
			 'Windswept Heath':4,
			 'Verdant Catacombs':3,
			 'Overgrown Tomb':1,
			 'Polluted Delta':1,
			 'Gavony Township':2,
			 'Swamp':1,
			 'Forest':2,
			 'Plains':2,
			 'Ghost Quarter':1,
			 "Vault of the Archangel":1,

			 'Noble Hierarch':3,
			 'Inquisition of Kozilek':2,
			 'Birds of Paradise':3,
			 'Lingering Souls':4,
			 'Path to Exile':3,
			 'Abrupt Decay':3,
			 'Voice of Resurgence':3,
			 'Loxodon Smiter':3,
			 'Kitchen Finks':2,
			 'Siege Rhino':4,
			 'Wilt-Leaf Liege':3,
			 "Qasali Pridemage":2,
			 "Sorin, Solemn Visitor":1,
			 "Elspeth, Knight-Errant":1,
		 },
side:{
			 'Duress':2,
			 'Zealous Persecution':2,
			 'Kor Firewalker':2,
			 'Choke':2,
			 'Kalitas, Traitor of Ghet':1,
			 "Kataki, War's Wage":2,
			 'Anguished Unmaking':2,
			 'Relic of Progenitus':2,
		 }
}
