{
	main:{
		'Breeding Pool':1,
		'Desolate Lighthouse':1,
		'Forest':1,
		'Island':3,
		'Misty Rainforest':4,
		'Mountain':1,
		'Steam Vents':3,
		'Stomping Ground':1,
		'Sulfur Falls':2,
		'Wandering Fumarole':1,
		'Wooded Foothills':4,
		'Snapcaster Mage':3,
		'Tarmogoyf':3,
		'Bounding Krasis':4,
		'Pestermite':4,
		'Kiki-jiki, Mirror Breaker':2,
		'Dispel':1,
		'Flame Slash':1,
		'Lightning Bolt':4,
		'Serum Visions':4,
		'Spell Snare':2,
		'Mana Leak':3,
		'Remand':4,
		'Dismember':1,
		'Electrolyze':1,
		'Cryptic Command':2,
		'Forked Bolt':1,
	},
	side:{
		'Dispel':2,
		'Relic of Progenitus':2,
		'Ancient Grudge':1,
		'Roast':1,
		'Anger of the Gods':2,
		'Izzet Staticaster':1,
		'Crumble to Dust':1,
		'Batterskull':1,
		'Thragthusk':1,
		'Destructive Revelry':1,
		'Kozilek\'s Return':1,
	}
}
