
{
	main:{
		'Tarmogoyf':4,
		'Hooting Mandrils':4,
		'Snapcaster Mage':1,
		'Delver of Secrets':4,
		'Serum Visions':4,
		'Gitaxian Probe':4,
		'Thought Scour':3,
		'Simic Charm':3,
		'Lightning Bolt':4,
		'Vapor Snag':1,
		'Stubborn Denial':3,
		'Mana Leak':3,
		'Disrupting Shoal':4,
		'Tarfire':1,
		'Steam Vents':2,
		'Misty Rainforest':4,
		'Scalding Tarn':4,
		'Wooded Foothills':1,
		'Stomping Ground':1,
		'Breeding Pool':1,
		'Island':3,
		'Forest':1,
	},
	side:{
		'Blood Moon':3,
		'Huntmaster of the Fells':4,
		'Forest':1,
		'Dispel':1,
		'Pyroclasm':2,
		'Ancient Grudge':2,
		'Natural State':1,
		'Dismember':1,
	}
}
