{
	main:{
		'Darksteel Citadel':4,
		'Glimmervoid':3,
		'Island':4,
		'Swamp':2,
		'Drowned Catacomb':4,
		'Underground River':4,
		'Academy Ruins':4,
		'Ornithopter':4,
		'Etherium Sculptor':4,
		'Steel Overseer':4,
		'Etched Champion':3,
		'Solemn Simulacrum':2,
		'Batterskull':2,
		'Wurmcoil Engine':2,
		'Disfigure':2,
		'Basilisk Collar':2,
		'Serum Visions':4,
		'Go for the Throat':2,
		'Ensoul Artifact':4,
		'Sculpting Steel':1,
		'Unwinding Clock':1,
		'Tezzeret, Agent of Bolas':2,
	},
	side:{
		'Master of Etherium':3,
		'Pithing Needle':3,
		'Ratchet Bomb':3,
		'Doom Blade':2,
		'Disfigure':2,
		'Dismember':2,
	}
}
