{
	main:{
		"Ornithopter":2 ,
		"Vault Skirge":4 ,
		"Etherium Sculptor":4 ,
		"Steel Overseer":4 ,
		"Solemn Simulacrum":2 ,
		"Batterskull":2 ,
		"Wurmcoil Engine":2 ,
		"Chalice of the Void":3 ,
		"Everflowing Chalice":3 ,
		"Ensoul Artifact":4 ,
		"Sculpting Steel":1 ,
		"Thoughtcast":4 ,
		"Tezzeret, Agent of Bolas":3 ,
		"Damnation":2 ,
		"Island":4 ,
		"Swamp":2 ,
		"Glimmervoid":3 ,
		"Watery Grave":2 ,
		"Academy Ruins":1 ,
		"Darksteel Citadel":4 ,
		"Underground River":4 ,
		"Urborg, Tomb of Yawgmoth":1 ,
	},
	side:{
		"Relic of Progenitus":3 ,
		"Defense Grid":3 ,
		"Pithing Needle":3 ,
		"Ratchet Bomb":3 ,
		"Dismember":2 ,
		"Doom Blade":1 ,
	}
}
