{
	main:{
		"Scalding Tarn":4, 
		"Flooded Strand":4, 
		"Steam Vents":2, 
		"Island":3, 
		"Mountain":1, 
		"Plains":1, 
		"Sulfur Falls":1, 
		"Sacred Foundry":1, 
		"Hallowed Fountain":1, 
		"Gitaxian Probe":4, 
		"Lightning Bolt":4, 
		"Lightning Hélix":4, 
		"Manamorphose":4, 
		"Boros Charm":2, 
		"Pyromancer Ascension":4, 
		"Thing in the Ice":4, 
		"Remand":3, 
		"Serum Visions":4, 
		"Visions of Beyond":4, 
		"Peek":2, 
		"Path to Exile":2, 
		"Mana Leak":2, 
	},
	side:{
		"Bedlam Reveler":2, 
		"Stony Silence":2, 
		"Wear/Tear":2, 
		"Dispel":2, 
		"Rest for the Waery":2, 
		"Grafdigger Cage":2, 
		"Blood Moon":3, 
	}
}
