{main:{
	"Ornithopter":3, 
	"Vault Skirge":4, 
	"Etherium Sculptor":4, 
	"Steel Overseer":4, 
	"Master of Etherium":1, 
	"Etched Champion":3, 
	"Batterskull":2, 
	"Sen Triplets":1, 
	"Mox Opal":4, 
	"Chalice of the Void":4, 
	"Ensoul Artifact":4, 
	"Deflecting Palm":2, 
	"Ghostly Prison":3, 
	"Tezzeret, Agent of Bolas":3, 
	"Plains":1, 
	"Academy Ruins":1, 
	"Mana Confluence":1, 
	"Island":2, 
	"Hallowed Fountain":2, 
	"Adarkar Wastes":4, 
	"Glimmervoid":4, 
	"Darksteel Citadel":4, 
},side:{
	"Tormod's Crypt":2, 
	"Ethersworn Canonist":2, 
	"Phyrexian Revoker":2, 
	"Disenchant":2, 
	"Spellskite":2, 
	"Whipflare":2, 
	"Surgical Extraction":1, 
	"Wrath of God":1, 
	"Torpor Orb":1, 
}}
