{
	main:{
		"Urza's Tower":4,
		"Urza's Mine":4,
		"Urza's Power Plant":4,
		"Oboro, Palace in the Clouds":1,
		"Academy Ruins":1,
		"Ghost Quarter":1,
		"Treasure Mage":2,
		"Wurmcoil Engine":1,
		"Thought-Knot Seer":1,
		"Steel Hellkite":1,
		"Platinum Angel":1,
		"Solemn Simulacrum":2,
		"Expedition Map":4,
		"Talisman of Dominance":1,
		"Oblivion Stone":1,
		"Mind Slaver":2,
		"Ugin, the Spirit Dragon":1,
		"Cyclonic Rift":1,
		"Condescendend":4,
		"Mana Leak":4,
		"Repeal":4,
		"Spell Burst":1,
		"Thirst for Knowledge":4,
		"Warping Wail":2,
	},
	side:{
		"Spellskite":2,
		"Sundering Titan":1,
		"Oblivion Stone":1,
		"Pithing Needle":2,
		"Ratchet Bomb":1,
		"Wurmcoil Engine":1,
		"Negate":1,
		"Dispel":1,
		"Hurkyl's Recall":4,
		"Flashfreeze":1,
	}
}
