{
	main:{
		'Urza\'s Mine':4,
		'Urza\'s Tower':4,
		'Urza\'s Power Plant':4,
		'Grove of the Burnwillows':2,
		'Karplusan Forest':1,
		'Forest':2,
		'Mountain':1,
		'Ghost Quarter':1,

		'Expedition Map':4,
		'Chromatic Sphere':4,
		'Chromatic Star':4,
		'Ancient Stirrings':4,
		'Sylvan Scrying':4,
		'Karn Liberated':3,
		'Ugin, the Spirit Dragon':3,
		'Oblivion Stone':3,
		'Wurmcoil Engine':3,
		'Batterskull':1,
		'Pyroclasm':4,
		'Platinum Angel':1,
		'Sundering Titan':1,
	},
	side:{
		'Relic of Progenitus':2,
		'Feed the Clan':2,
		'Choke':1,
		'Chalice of the Void':3,
		'Dismember':1,
		'Torpor Orb':2,
		"Nature's Claim":2,
		'Creeping Corrosion':2,
	}
}
