{
	main:{
		"Plains":1, 
		"Sacred Foundry":1, 
		"Valakut, the molten pinacle":4, 
		"Mountain":5, 
		"Wooded Foothills":4, 
		"Windswepth Heath":1, 
		"Stomping Ground":4, 
		"Cinder Glade":3, 
		"Forest":2, 
		"Emrakul, the aeons torn":1, 
		"Courser of Kruphix":2, 
		"Sakura Tribe-Elder":4, 
		"Primeval titan":4, 
		"Search for Tomorrow":4, 
		"Through the Breach":4, 
		"Anger of the Gods":2, 
		"Summoner's Pact":3, 
		"Scapeshift":2, 
		"Farseek":4, 
		"Oath of Nissa":2, 
		"Nahiri, the Harbinger":3, 
	},
	side:{
		"Obstinate Baloth":3,	
		"Sudden Shock":3, 
		"Krosan Grip":2, 
		"Crumble to Dust":2, 
		"Relic of Progenitus":2, 
		"Ancient Grudge":1, 
		"Anger of the Gods":1, 
		"Melira, Sylvok Outcast":1, 
	}
}

