{
	main:{
		"Blood Moon":1, 
		"Spell Snare":2, 
		"Serum Visions":4, 
		"Twisted Image":1, 
		"Izzet Charm":1, 
		"Gut Shot":1, 
		"Remand":4, 
		"Lightning Bolt":4, 
		"Snapcaster Mage":3, 
		"Mana Leak":3, 
		"Bedlam Reveler":2, 
		"Electrolyze":2, 
		"Delver of Secrets":4, 
		"Vapor Snag":1, 
		"Gitaxian Probe":4, 
		"Thing in the Ice":4, 
		"Negate":1, 
		"Spell Pierce":1, 
		"Spirebluff Canal":4, 
		"Island":2, 
		"Scalding Tarn":4, 
		"Steam Vents":4, 
		"Wandering Fumarole":1, 
		"Cascade Bluffs":1, 
		"Mountain":2, 
	},
	side:{
		"Spell Pierce":1, 
		"Vendilion Clique":1, 
		"Vapor Snag":1, 
		"Volcanic Fallout":2, 
		"Spellskite":1, 
		"Izzet Staticaster":1, 
		"Smash to Smithereens":2, 
		"Pithing Needle":2, 
		"Sudden Shock":2, 
		"Twisted Image":1, 
	}
}
