{
	main:{
		'Delver of Secrets':4,
		"Monastery Swiftspear":4 ,
		"Young Pyromancer":4 ,
		'Snapcaster Mage':4,
		'Serum Visions':4,
		"Gitaxian Probe":1 ,
		'Lightning Bolt':4,
		'Burst Lightning':4,
		'Electrolyze':2,
		'Remand':3,
		'Vapor Snag':3,
		"Blood Moon":4 ,
		'Misty Rainforest':4,
		'Scalding Tarn':4,
		'Steam Vents':2,
		'Island':7,
		'Mountain':3,
		'Sulfur Falls':1,
	},
	side:{
		"Pia and Kiran Nalaar":1 ,
		"Batterskull":1 ,
		'Negate':1,
		'Dispel':3,
		"Invasive Surgery":1 ,
		"Izzet Staticaster":1 ,
		"Forked Bolt":1 ,
		"Vandalblast":1 ,
		"Counterflux":1 ,
		'Spellskite':1,
		'Relic of Progenitus':2,
		'Flame Slash':1,
	}
}
