{
	main:{
		"Grim Lavamancer":1,
		"Snapcaster Mage":4,
		"Deceiver Exarch":4,
		"Pestermite":1,
		"Vendilion Clique":1,
		"Kiki-jiki, Mirror Breaker":3,

		"Ancestral Vision":3,
		"Flame Slash":1,
		"Lightning Bolt":4,
		"Serum Visions":4,
		"Spell Snare":2,
		"Mana Leak":1,
		"Remand":3,
		"Electrolyze":2,
		"Cryptic Command":2,

		"Cascade Bluffs":1,
		"Desolate Lighthouse":1,
		"Ghost Quarter":1,
		"Island":4,
		"Minamo, School at Water's Edge":1,
		"Mountain":1,
		"Oboro, Palace in the Clouds":1,
		"Polluted Delta":3,
		"Scalding Tarn":4,
		"Steam Vents":3,
		"Sulfur Falls":2,
		"Wandering Fumarole":2,
	},
	side:{
		"Izzet Staticaster":1 ,
		"Goblin Dark-Dwellers":1,
		"Ancestral Vision":1,
		"Engineered Explosives":1,
		"Dispel":2,
		"Flame Slash":1,
		"Negate":1,
		"Roast":1,
		"Anger of the Gods":2,
		"Molten Rain":3,
		"Wurmcoil Engine":1,
	}
}
