{main:{
		"Jace, Vryn's Prodigy":1, 
		"Snapcaster Mage":4, 
		"Deceiver Exarch":4, 
		"Vendilion Clique":1, 
		"Izzet Charm":1, 
		"Kiki-jiki, Mirror Breaker":2, 
		"Ancestral Vision":3, 
		"Flame Slash":2, 
		"Lightning Bolt":4, 
		"Serum Visions":4, 
		"Spell Snare":2, 
		"Remand":3, 
		"Mana Leak":1, 
		"Electrolyze":2, 
		"Cryptic Command":3, 
		"Cascade Bluffs":1, 
		"Desolate Lighthouse":1, 
		"Ghost Quarter":1, 
		"Island":4, 
		"Mountain":1, 
		"Polluted Delta":3, 
		"Scalding Tarn":4, 
		"Steam Vents":3, 
		"Sulfur Falls":2, 
		"Wandering Fumarole":1, 
		"Minamo,School at Water's Edge":1, 
		"Oboro, Palace in the Clouds":1, 
},side:{
		"Izzet Staticaster":2, 
		"Molten Rain":3, 
		"Engineered Explosives":1, 
		"Dispel":2, 
		"Relic of Progenitus":1, 
		"Negate":1, 
		"Roast":1, 
		"Anger of the Gods":2, 
		"Blood Moon":1, 
		"Goblin Dark-Dwellers":1, 
}}
