{
	main:{
		'Snapcaster Mage':3,
		"Deceiver Exarch":4,
		"Pestermite":2,
		"Vendilion Clique":1,
		"Kiki-jiki, Mirror Breaker":3,

		'Ancestral Vision':4,
		"Dispel":1,
		"Flame Slash":1,
		'Lightning Bolt':4,
		'Serum Visions':4,
		"Spell Snare":1,
		'Remand':3,
		"Anger of the Gods":1,
		'Electrolyze':2,
		"Cryptic Command":2,

		"Cascade Bluffs":1,
		"Desolate Lighthouse":2,
		"Ghost Quarter":1,
		'Island':5,
		'Mountain':1,
		'Polluted Delta':4,
		'Scalding Tarn':4,
		'Steam Vents':3,
		'Sulfur Falls':2,
		"Wandering Fumarole":1,
	},
	side:{
		'Spellskite':1,
		"Izzet Staticaster":1 ,
		"Keranos, God of Storms":1,
		"Teferi, Mage of Zhalfir":1,
		"Engineered Explosives":1,
		'Dispel':2,
		'Relic of Progenitus':2,
		'Negate':1,
		"Roast":1,
		"Sun Droplet":1,
		"Anger of the Gods":1,
		"Blood Moon":2,
	}
}
