{main:{
	"Oblivion Stone ":1, 
	"Mindslaver":1, 
	"Sundering Titan ":2, 
	"Platinum Angel":1, 
	"Talisman of Dominance":2, 
	"Wurmcoil Engine":2, 
	"Expedition Map":4, 
	"Spell Burst":1, 
	"Remand":4, 
	"Thirst for Knowledge":4, 
	"Treasure Mage":2, 
	"Fabricate":1, 
	"Repeal ":3, 
	"Condescendend":4, 
	"Remand":4, 
	"Ugin,the Spirit Dragon":1, 
	"Ulamog, the cearless hunger":1, 
	"Snapcaster Mage":1, 
	"Elder Deep-Fiend":1, 
	"Island":6, 
	"Urza's Mine":4, 
	"Urza's Power Plant":4, 
	"Urza's Tower":4, 
	"Academy Ruins":1, 
	"Ghost Quarter":1, 
	"Oboro, Palace in the clouds":1, 
},side:{
	"Ugin,the Spirit Dragon":1, 
	"Ulamog, the cearless hunger":1, 
	"Inkwell Leviathan":1, 
	"Dispel":1, 
	"Negate":1, 
	"Torpor Orb":2, 
	"Aetherize":2, 
	"Mindslaver":1, 
	"Gravediger's Cage":1, 
	"Chalice of the Void":2, 
	"Piting Needle":2, 
}}

