{
	main:{
		"Geist of Saint Traft":2,
		"Path to Exile":3,
		"Aether Spellbomb":2,
		"Detention Sphere":2,
		"Wall of Omens":4,
		"Court Hussar":2,
		"Sun Titan":4,
		"Pilgrim's Eye":4,
		"Phantasmal Image":1,
		"Remand":2,
		"Mana Leak":2,
		"Supreme Verdict":2,
		"Restoration Angel":2,
		"Kitchen Finks":2,
		"Ancestral Vision":1,
		"Flickerwisp":4,
		"Hallowed Fountain":3,
		"Flooded Strand":2,
		"Emeria, the Sky Ruin":3,
		"Ghost Quarter":1,
		"Plains":9,
		"Island":2,
	},
	side:{
		"Vendilion Clique":2,
		"Kataki, War's Wage":1,
		"Mortarpod":2,
		"Pithing Needle":1,
		"Wrath of God":2,
		"Swan Song":1,
		"Dispel":2,
		"Path to Exile":1,
		"Wheel of Sun and Moon":1,
		"Detention Sphere":1,
	}
}
