{
	main:{
		'Urza\'s Mine':4,
		'Urza\'s Power Plant':4,
		'Urza\'s Tower':4,
		'Ghost Quarter':1,
		'Academy Ruins':1,
		'Island':10,
		'Remand':4,
		'Condescend':3,
		'Repeal':3,
		'Expedition Map':4,
		'Talisman of Dominance':3,
		'Thirst for Knowledge':3,
		'Spell Burst':1,
		'Ugin, the Spirit Dragon':2,
		'Mind Slaver':2,
		'Batterskull':2,
		'Wurmcoil Engine':3,
		'Platinum Angel':1,
		'Cyclonic Rift':1,
		'Oblivion Stone':1,
		'Sundering Titan':1,
		'Fabricate':1,
		'Solemn Simulacrum':1,
		'Mana Leak':1,

	},
	side:{
		'Hurkyl\'s Recall':1,
		'Spatial Contortion':2,
		'Dismember':1,
		'Aetherize':1,
		'Tormod\'s Crypt':2,
		'Surgical Extraction':1,
		'Dispel':1,
		'Chalice of the Void':3,
	}
}
