{
	main:{
		"Arid Mesa":4 ,
		"Atarka's Command":4 ,
		"Boros Charm":3 ,
		"Experiment One":2 ,
		"Forest":1 ,
		"Ghor-Clan Rampager":2 ,
		"Goblin Guide":2 ,
		"Kird Ape":4 ,
		"Lightning Bolt":4 ,
		"Loam Lion":4 ,
		"Loxodon Smiter":3 ,
		"Mountain":1 ,
		"Path to Exile":4 ,
		"Plains":1 ,
		"Sacred Foundry":2 ,
		"Stomping Ground":2 ,
		"Tarmogoyf":4 ,
		"Temple Garden":1 ,
		"Wild Nacatl":4 ,
		"Windswept Heath":4 ,
		"Wooded Foothills":4 ,
	},
	side:{
		"Ancient Grudge":1 ,
		"Destructive Revelry":2 ,
		"Gut Shot":1 ,
		"Kitchen Finks":2 ,
		"Lightning Helix":2 ,
		"Mutagenic Growth":2 ,
		"Stony Silence":2 ,
		"Tormod's Crypt":2 ,
		"Volcanic Fallout":1 ,
	},
}
