{
	main:{
		"Kird Ape":4 ,
		"Dryad Arbor":1 ,
		"Goblin Guide":4 ,
		"Burning-Tree Emissary":4 ,
		"Vexing Devil":2 ,
		"Wild Nacatl":4 ,
		"Reckless Bushwacker":4 ,
		"Ghor-Clan Rampager":2 ,
		"Path to Exile":3 ,
		"Atarka's Command":4 ,
		"Mutagenic Growth":2 ,
		"Lightning Helix":4 ,
		"Lightning Bolt":4 ,

		"Sacred Foundry":2 ,
		"Temple Garden":2 ,
		"Stomping Ground":3 ,
		"Arid Mesa":1,
		"Wooded Foothills":4 ,
		"Windswept Heath":4 ,
		"Mountain":1 ,
		"Forest":1 ,
	},
	side:{
		"Grim Lavamancer":1,
		"Eidolon of the Great Revel":1,
		"Smash to Smithereens":2,
		"Stony Silence":2 ,
		"Ancient Grudge":2 ,
		"Destructive Revelry":2 ,
		"Path to Exile":1 ,
		"Scavenging Ooze":2,
		"Phyrexian Unlife":1,
		"Spellskite":1,
	},
}
