{
	main:{
		"Goblin Guide":4, 
		"Kird Ape":4, 
		"Wild Nacatl":4, 
		"Burning-Tree Emissary":4, 
		"Reckless Bushwhacker":3, 
		"Experiment One":3, 
		"Vexing Devil":2, 
		"Flinthoof Boar":2, 
		"Ghor-Clan Rampager":3, 
		"Atarka's Command":3, 
		"Lightning Bolt":4, 
		"Path to Exile":3, 
		"Mutagenic Growth":3, 
		"Forest":2, 
		"Mountain":3, 
		"Plains":1, 
		"Stomping Ground":2, 
		"Sacred Foundry":2, 
		"Windswept Heath":4, 
		"Wooded Foothills":4, 
	},
	side:{
		"Boros Charm":2, 
		"Lightning Helix":2, 
		"Destructive Revelry":3, 
		"Experiment One":1, 
		"Become Immense":1, 
		"Rancor":1, 
		"Reckless Bushwhacker":1, 
		"Ghor-Clan Rampager":1, 
		"Arliin Kord":1, 
		"Grafdigger's Cage":2, 
	},
}
